-- PTPN built-in library. Safe to re-run (deterministic ids, on conflict do nothing).
create or replace function pg_temp.sid(t text) returns uuid language sql immutable as $$ select extensions.uuid_generate_v5('6f1c1e4a-8d3b-4c55-9a9e-5b1d2e7c0a11'::uuid, t) $$;

insert into public.exercises (id, name, muscle, equipment, category, instructions) values
(pg_temp.sid('ex:Barbell bench press'),'Barbell bench press','Chest','Barbell','strength','Feet planted, shoulder blades pinched, lower the bar to mid-chest and press up.'),
(pg_temp.sid('ex:Incline barbell bench press'),'Incline barbell bench press','Chest','Barbell','strength','Bench at 30 degrees, bar to upper chest, elbows about 45 degrees from the body.'),
(pg_temp.sid('ex:Dumbbell bench press'),'Dumbbell bench press','Chest','Dumbbells','strength','Lower the dumbbells to chest level with control, press up and slightly together.'),
(pg_temp.sid('ex:Incline dumbbell press'),'Incline dumbbell press','Chest','Dumbbells','strength','Bench at 30 degrees, press from upper chest, keep wrists stacked over elbows.'),
(pg_temp.sid('ex:Dumbbell fly'),'Dumbbell fly','Chest','Dumbbells','strength','Soft elbows, open wide until you feel a chest stretch, hug back up.'),
(pg_temp.sid('ex:Cable crossover'),'Cable crossover','Chest','Cable','strength','Step forward, bring handles together in a wide arc in front of the chest.'),
(pg_temp.sid('ex:Machine chest press'),'Machine chest press','Chest','Machine','strength','Handles at mid-chest, press without locking out hard, control the return.'),
(pg_temp.sid('ex:Push-up'),'Push-up','Chest','Bodyweight','strength','Hands under shoulders, body in one line, chest to just above the floor.'),
(pg_temp.sid('ex:Dips'),'Dips','Chest','Bodyweight','strength','Lean slightly forward, lower until shoulders are level with elbows, press up.'),
(pg_temp.sid('ex:Deadlift'),'Deadlift','Back','Barbell','strength','Bar over mid-foot, flat back, push the floor away and stand tall.'),
(pg_temp.sid('ex:Barbell row'),'Barbell row','Back','Barbell','strength','Hinge to 45 degrees, pull the bar to the lower ribs, control down.'),
(pg_temp.sid('ex:Pull-up'),'Pull-up','Back','Bodyweight','strength','Overhand grip, pull chest toward the bar, full hang at the bottom.'),
(pg_temp.sid('ex:Chin-up'),'Chin-up','Back','Bodyweight','strength','Underhand grip, drive elbows down, chin over the bar.'),
(pg_temp.sid('ex:Lat pulldown'),'Lat pulldown','Back','Cable','strength','Slight lean back, pull the bar to the upper chest, elbows down and in.'),
(pg_temp.sid('ex:Seated cable row'),'Seated cable row','Back','Cable','strength','Tall chest, row the handle to the stomach, squeeze shoulder blades.'),
(pg_temp.sid('ex:Single-arm dumbbell row'),'Single-arm dumbbell row','Back','Dumbbells','strength','Hand and knee on bench, row the dumbbell to the hip.'),
(pg_temp.sid('ex:T-bar row'),'T-bar row','Back','Barbell','strength','Chest up, row the handle to the chest, keep the back flat.'),
(pg_temp.sid('ex:Face pull'),'Face pull','Shoulders','Cable','strength','Rope at face height, pull to the forehead with elbows high, rotate out.'),
(pg_temp.sid('ex:Inverted row'),'Inverted row','Back','Bodyweight','strength','Body straight under a bar, pull chest to the bar.'),
(pg_temp.sid('ex:Straight-arm pulldown'),'Straight-arm pulldown','Back','Cable','strength','Arms long, sweep the bar down to the thighs using the lats.'),
(pg_temp.sid('ex:Overhead press'),'Overhead press','Shoulders','Barbell','strength','Bar from the front rack, press overhead, head through at the top.'),
(pg_temp.sid('ex:Seated dumbbell shoulder press'),'Seated dumbbell shoulder press','Shoulders','Dumbbells','strength','Back supported, press from ear height to overhead.'),
(pg_temp.sid('ex:Arnold press'),'Arnold press','Shoulders','Dumbbells','strength','Start palms facing you, rotate out as you press overhead.'),
(pg_temp.sid('ex:Lateral raise'),'Lateral raise','Shoulders','Dumbbells','strength','Slight bend in elbows, raise out to shoulder height, slow down.'),
(pg_temp.sid('ex:Rear delt fly'),'Rear delt fly','Shoulders','Dumbbells','strength','Hinge forward, raise arms out wide leading with the elbows.'),
(pg_temp.sid('ex:Landmine press'),'Landmine press','Shoulders','Barbell','strength','Half-kneeling, press the bar end up and forward.'),
(pg_temp.sid('ex:Push press'),'Push press','Shoulders','Barbell','strength','Short dip at the knees, drive with the legs and press overhead.'),
(pg_temp.sid('ex:Back squat'),'Back squat','Quads','Barbell','strength','Bar on upper back, brace, sit down between the hips, drive up.'),
(pg_temp.sid('ex:Front squat'),'Front squat','Quads','Barbell','strength','Bar in front rack, elbows high, squat upright.'),
(pg_temp.sid('ex:Goblet squat'),'Goblet squat','Quads','Kettlebell','strength','Hold the weight at the chest, squat deep with an upright torso.'),
(pg_temp.sid('ex:Leg press'),'Leg press','Quads','Machine','strength','Feet shoulder width, lower until knees are near 90 degrees, press.'),
(pg_temp.sid('ex:Bulgarian split squat'),'Bulgarian split squat','Quads','Dumbbells','strength','Rear foot on bench, drop the back knee, drive through the front heel.'),
(pg_temp.sid('ex:Walking lunge'),'Walking lunge','Quads','Dumbbells','strength','Long step, back knee toward the floor, step through.'),
(pg_temp.sid('ex:Reverse lunge'),'Reverse lunge','Quads','Bodyweight','strength','Step back, lower both knees to 90 degrees, return.'),
(pg_temp.sid('ex:Step-up'),'Step-up','Quads','Dumbbells','strength','Whole foot on the box, drive up through the front leg.'),
(pg_temp.sid('ex:Leg extension'),'Leg extension','Quads','Machine','strength','Extend the knees fully, pause, lower with control.'),
(pg_temp.sid('ex:Hack squat'),'Hack squat','Quads','Machine','strength','Back against the pad, squat deep, press through mid-foot.'),
(pg_temp.sid('ex:Romanian deadlift'),'Romanian deadlift','Hamstrings','Barbell','strength','Soft knees, push hips back until a hamstring stretch, stand up.'),
(pg_temp.sid('ex:Hip thrust'),'Hip thrust','Glutes','Barbell','strength','Upper back on bench, drive hips up, squeeze glutes at the top.'),
(pg_temp.sid('ex:Glute bridge'),'Glute bridge','Glutes','Bodyweight','strength','Feet flat, drive hips up, ribs down, pause at the top.'),
(pg_temp.sid('ex:Lying leg curl'),'Lying leg curl','Hamstrings','Machine','strength','Curl heels toward glutes, hips pressed into the pad.'),
(pg_temp.sid('ex:Seated leg curl'),'Seated leg curl','Hamstrings','Machine','strength','Curl under, pause, return slowly.'),
(pg_temp.sid('ex:Good morning'),'Good morning','Hamstrings','Barbell','strength','Bar on back, hinge forward with a flat back, stand up.'),
(pg_temp.sid('ex:Kettlebell swing'),'Kettlebell swing','Glutes','Kettlebell','strength','Hike the bell back, snap the hips forward, float it to chest height.'),
(pg_temp.sid('ex:Nordic hamstring curl'),'Nordic hamstring curl','Hamstrings','Bodyweight','strength','Knees anchored, lower the body forward as slowly as possible.'),
(pg_temp.sid('ex:Single-leg Romanian deadlift'),'Single-leg Romanian deadlift','Hamstrings','Dumbbells','strength','Hinge on one leg, back leg long, keep hips square.'),
(pg_temp.sid('ex:Cable pull-through'),'Cable pull-through','Glutes','Cable','strength','Face away from the cable, hinge, drive hips through.'),
(pg_temp.sid('ex:Sumo deadlift'),'Sumo deadlift','Glutes','Barbell','strength','Wide stance, hands inside knees, push knees out and stand.'),
(pg_temp.sid('ex:Trap bar deadlift'),'Trap bar deadlift','Quads','Trap bar','strength','Stand in the bar, brace, push the floor away.'),
(pg_temp.sid('ex:Standing calf raise'),'Standing calf raise','Calves','Machine','strength','Full stretch at the bottom, rise high, pause.'),
(pg_temp.sid('ex:Seated calf raise'),'Seated calf raise','Calves','Machine','strength','Knees under the pad, full range, slow tempo.'),
(pg_temp.sid('ex:Barbell curl'),'Barbell curl','Biceps','Barbell','strength','Elbows by your sides, curl without swinging.'),
(pg_temp.sid('ex:Dumbbell curl'),'Dumbbell curl','Biceps','Dumbbells','strength','Supinate as you curl, lower slowly.'),
(pg_temp.sid('ex:Hammer curl'),'Hammer curl','Biceps','Dumbbells','strength','Neutral grip, curl to the shoulder, elbows fixed.'),
(pg_temp.sid('ex:Preacher curl'),'Preacher curl','Biceps','EZ bar','strength','Arms on the pad, curl up, lower to near straight.'),
(pg_temp.sid('ex:Cable curl'),'Cable curl','Biceps','Cable','strength','Constant tension, squeeze at the top.'),
(pg_temp.sid('ex:Triceps pushdown'),'Triceps pushdown','Triceps','Cable','strength','Elbows pinned, push down to full lockout.'),
(pg_temp.sid('ex:Overhead triceps extension'),'Overhead triceps extension','Triceps','Dumbbells','strength','Weight behind the head, extend overhead, elbows forward.'),
(pg_temp.sid('ex:Skull crusher'),'Skull crusher','Triceps','EZ bar','strength','Lower the bar toward the forehead, extend back up.'),
(pg_temp.sid('ex:Close-grip bench press'),'Close-grip bench press','Triceps','Barbell','strength','Hands shoulder width, elbows tucked, press.'),
(pg_temp.sid('ex:Bench dip'),'Bench dip','Triceps','Bodyweight','strength','Hands on bench behind you, lower to 90 degrees, press up.'),
(pg_temp.sid('ex:Plank'),'Plank','Core','Bodyweight','core','Forearms down, body straight, squeeze glutes and brace.'),
(pg_temp.sid('ex:Side plank'),'Side plank','Core','Bodyweight','core','Elbow under shoulder, hips high, body in one line.'),
(pg_temp.sid('ex:Dead bug'),'Dead bug','Core','Bodyweight','core','Low back flat, extend opposite arm and leg slowly.'),
(pg_temp.sid('ex:Hanging leg raise'),'Hanging leg raise','Core','Bodyweight','core','Hang from a bar, raise legs without swinging.'),
(pg_temp.sid('ex:Cable crunch'),'Cable crunch','Core','Cable','core','Kneel, crunch the ribs toward the hips.'),
(pg_temp.sid('ex:Ab wheel rollout'),'Ab wheel rollout','Core','Ab wheel','core','Roll out with a braced core, pull back without arching.'),
(pg_temp.sid('ex:Russian twist'),'Russian twist','Core','Bodyweight','core','Lean back, rotate side to side from the ribs.'),
(pg_temp.sid('ex:Pallof press'),'Pallof press','Core','Cable','core','Stand side-on to the cable, press out and resist rotation.'),
(pg_temp.sid('ex:Bird dog'),'Bird dog','Core','Bodyweight','core','On all fours, reach opposite arm and leg, keep hips level.'),
(pg_temp.sid('ex:Hollow hold'),'Hollow hold','Core','Bodyweight','core','Low back pressed down, arms and legs extended, hold.'),
(pg_temp.sid('ex:Mountain climber'),'Mountain climber','Core','Bodyweight','cardio','Plank position, drive knees to chest quickly.'),
(pg_temp.sid('ex:Farmer''s carry'),'Farmer''s carry','Full body','Dumbbells','strength','Heavy weights at your sides, walk tall with short steps.'),
(pg_temp.sid('ex:Box jump'),'Box jump','Legs','Box','plyometric','Swing arms, jump onto the box, land softly, step down.'),
(pg_temp.sid('ex:Broad jump'),'Broad jump','Legs','Bodyweight','plyometric','Jump forward as far as possible, stick the landing.'),
(pg_temp.sid('ex:Jump squat'),'Jump squat','Legs','Bodyweight','plyometric','Quarter squat, explode up, land softly into the next rep.'),
(pg_temp.sid('ex:Medicine ball slam'),'Medicine ball slam','Full body','Medicine ball','plyometric','Reach tall, slam the ball down hard, catch and repeat.'),
(pg_temp.sid('ex:Burpee'),'Burpee','Full body','Bodyweight','cardio','Squat, kick back to plank, chest down, jump up.'),
(pg_temp.sid('ex:Skater jump'),'Skater jump','Legs','Bodyweight','plyometric','Bound side to side, land on one leg with control.'),
(pg_temp.sid('ex:Tuck jump'),'Tuck jump','Legs','Bodyweight','plyometric','Jump and drive knees to the chest.'),
(pg_temp.sid('ex:Power clean'),'Power clean','Full body','Barbell','strength','Pull from the floor, extend hard, catch in the front rack.'),
(pg_temp.sid('ex:Hang clean'),'Hang clean','Full body','Barbell','strength','Start at mid-thigh, jump and shrug, catch in the front rack.'),
(pg_temp.sid('ex:Thruster'),'Thruster','Full body','Barbell','strength','Front squat straight into an overhead press.'),
(pg_temp.sid('ex:Wall ball'),'Wall ball','Full body','Medicine ball','strength','Squat, then drive the ball to a target on the wall.'),
(pg_temp.sid('ex:Running'),'Running','Cardio','None','cardio','Easy, conversational pace unless stated.'),
(pg_temp.sid('ex:Treadmill run'),'Treadmill run','Cardio','Treadmill','cardio','Set speed and incline as prescribed.'),
(pg_temp.sid('ex:Rowing machine'),'Rowing machine','Cardio','Rower','cardio','Legs, then body, then arms; reverse on the way back.'),
(pg_temp.sid('ex:Assault bike'),'Assault bike','Cardio','Air bike','cardio','Push and pull with arms and legs together.'),
(pg_temp.sid('ex:Cycling'),'Cycling','Cardio','Bike','cardio','Steady cadence at the prescribed effort.'),
(pg_temp.sid('ex:Jump rope'),'Jump rope','Cardio','Rope','cardio','Small hops on the balls of the feet.'),
(pg_temp.sid('ex:Sled push'),'Sled push','Full body','Sled','cardio','Low body angle, drive with short powerful steps.'),
(pg_temp.sid('ex:Stair climber'),'Stair climber','Cardio','Machine','cardio','Upright posture, avoid leaning on the rails.'),
(pg_temp.sid('ex:Ski erg'),'Ski erg','Cardio','Ski erg','cardio','Hinge and pull down with the arms and core.'),
(pg_temp.sid('ex:Battle ropes'),'Battle ropes','Full body','Ropes','cardio','Athletic stance, fast alternating waves.'),
(pg_temp.sid('ex:World''s greatest stretch'),'World''s greatest stretch','Mobility','Bodyweight','mobility','Lunge, elbow to instep, rotate and reach to the ceiling.'),
(pg_temp.sid('ex:Hip 90/90'),'Hip 90/90','Mobility','Bodyweight','mobility','Both knees at 90 degrees, rotate side to side tall.'),
(pg_temp.sid('ex:Cat-cow'),'Cat-cow','Mobility','Bodyweight','mobility','On all fours, alternate rounding and arching the spine.'),
(pg_temp.sid('ex:Thoracic rotation'),'Thoracic rotation','Mobility','Bodyweight','mobility','Side-lying, open the top arm and follow it with your eyes.'),
(pg_temp.sid('ex:Couch stretch'),'Couch stretch','Mobility','Bodyweight','mobility','Back knee against the wall, squeeze the glute, stay tall.'),
(pg_temp.sid('ex:Pigeon stretch'),'Pigeon stretch','Mobility','Bodyweight','mobility','Front shin across, sink hips toward the floor.'),
(pg_temp.sid('ex:Band pull-apart'),'Band pull-apart','Shoulders','Band','mobility','Arms straight, pull the band apart to the chest.'),
(pg_temp.sid('ex:Hamstring stretch'),'Hamstring stretch','Mobility','Bodyweight','mobility','Leg straight on a low step, hinge forward gently.'),
(pg_temp.sid('ex:Shoulder dislocates'),'Shoulder dislocates','Mobility','Band','mobility','Wide grip, pass the band over and behind the head.'),
(pg_temp.sid('ex:Deep squat hold'),'Deep squat hold','Mobility','Bodyweight','mobility','Sit in the bottom of a squat, chest tall, breathe.')
on conflict (id) do nothing;

insert into public.foods (id, name, serving_label, serving_g, kcal, protein, carbs, fat) values
(pg_temp.sid('food:Chicken breast, cooked'),'Chicken breast, cooked','100 g',100,165,31,0,3.6),
(pg_temp.sid('food:Chicken thigh, cooked, skinless'),'Chicken thigh, cooked, skinless','100 g',100,209,26,0,10.9),
(pg_temp.sid('food:Turkey breast, cooked'),'Turkey breast, cooked','100 g',100,135,30,0,1),
(pg_temp.sid('food:Beef mince 5% fat, cooked'),'Beef mince 5% fat, cooked','100 g',100,170,26,0,7),
(pg_temp.sid('food:Sirloin steak, cooked'),'Sirloin steak, cooked','100 g',100,206,30,0,9),
(pg_temp.sid('food:Pork tenderloin, cooked'),'Pork tenderloin, cooked','100 g',100,143,26,0,3.5),
(pg_temp.sid('food:Bacon rashers, grilled'),'Bacon rashers, grilled','1 rasher (25 g)',25,287,23.4,0.1,21.6),
(pg_temp.sid('food:Ham, sliced'),'Ham, sliced','1 slice (30 g)',30,107,18,1.5,3.3),
(pg_temp.sid('food:Salmon fillet, cooked'),'Salmon fillet, cooked','100 g',100,206,22,0,12),
(pg_temp.sid('food:Smoked salmon'),'Smoked salmon','100 g',100,117,18.3,0,4.3),
(pg_temp.sid('food:Tuna, canned in water, drained'),'Tuna, canned in water, drained','1 can (110 g)',110,116,26,0,1),
(pg_temp.sid('food:Tuna steak, cooked'),'Tuna steak, cooked','100 g',100,184,30,0,6.3),
(pg_temp.sid('food:Cod, cooked'),'Cod, cooked','100 g',100,105,23,0,0.9),
(pg_temp.sid('food:Mackerel, cooked'),'Mackerel, cooked','100 g',100,262,23.9,0,17.8),
(pg_temp.sid('food:Sardines, canned in oil, drained'),'Sardines, canned in oil, drained','100 g',100,208,24.6,0,11.5),
(pg_temp.sid('food:Prawns, cooked'),'Prawns, cooked','100 g',100,99,24,0.2,0.3),
(pg_temp.sid('food:Eggs, whole'),'Eggs, whole','1 large egg (50 g)',50,143,12.6,0.7,9.5),
(pg_temp.sid('food:Egg whites'),'Egg whites','100 g',100,52,11,0.7,0.2),
(pg_temp.sid('food:Greek yogurt 0% fat'),'Greek yogurt 0% fat','100 g',100,59,10.3,3.6,0.4),
(pg_temp.sid('food:Greek yogurt, full fat'),'Greek yogurt, full fat','100 g',100,97,9,4,5),
(pg_temp.sid('food:Skyr, plain'),'Skyr, plain','1 pot (150 g)',150,63,11,4,0.2),
(pg_temp.sid('food:Cottage cheese, low fat'),'Cottage cheese, low fat','100 g',100,72,12.4,2.7,1),
(pg_temp.sid('food:Whey protein powder'),'Whey protein powder','1 scoop (30 g)',30,400,80,8,6),
(pg_temp.sid('food:Protein bar'),'Protein bar','1 bar (60 g)',60,350,33,35,10),
(pg_temp.sid('food:Tofu, firm'),'Tofu, firm','100 g',100,144,15.8,2.8,8.7),
(pg_temp.sid('food:Tempeh'),'Tempeh','100 g',100,192,20,7.6,11),
(pg_temp.sid('food:Lentils, cooked'),'Lentils, cooked','100 g',100,116,9,20,0.4),
(pg_temp.sid('food:Chickpeas, cooked'),'Chickpeas, cooked','100 g',100,164,8.9,27.4,2.6),
(pg_temp.sid('food:Black beans, cooked'),'Black beans, cooked','100 g',100,132,8.9,23.7,0.5),
(pg_temp.sid('food:Kidney beans, cooked'),'Kidney beans, cooked','100 g',100,127,8.7,22.8,0.5),
(pg_temp.sid('food:Edamame'),'Edamame','100 g',100,121,11.9,8.9,5.2),
(pg_temp.sid('food:Milk, semi-skimmed'),'Milk, semi-skimmed','250 ml glass',250,46,3.4,4.7,1.7),
(pg_temp.sid('food:Milk, whole'),'Milk, whole','250 ml glass',250,64,3.3,4.7,3.6),
(pg_temp.sid('food:Almond milk, unsweetened'),'Almond milk, unsweetened','250 ml glass',250,13,0.5,0.3,1.1),
(pg_temp.sid('food:Cheddar cheese'),'Cheddar cheese','30 g',30,403,25,1.3,33),
(pg_temp.sid('food:Mozzarella'),'Mozzarella','100 g',100,280,28,3.1,17),
(pg_temp.sid('food:Feta'),'Feta','30 g',30,264,14,4,21),
(pg_temp.sid('food:Parmesan'),'Parmesan','10 g',10,431,38,4.1,29),
(pg_temp.sid('food:Halloumi'),'Halloumi','100 g',100,316,21,2.2,25),
(pg_temp.sid('food:White rice, cooked'),'White rice, cooked','1 cup (160 g)',160,130,2.7,28,0.3),
(pg_temp.sid('food:Brown rice, cooked'),'Brown rice, cooked','1 cup (160 g)',160,123,2.7,25.6,1),
(pg_temp.sid('food:Pasta, cooked'),'Pasta, cooked','100 g',100,158,5.8,31,0.9),
(pg_temp.sid('food:Wholewheat pasta, cooked'),'Wholewheat pasta, cooked','100 g',100,149,5.9,30,1.7),
(pg_temp.sid('food:Egg noodles, cooked'),'Egg noodles, cooked','100 g',100,138,4.5,25,2.1),
(pg_temp.sid('food:Rice noodles, cooked'),'Rice noodles, cooked','100 g',100,108,1.8,24,0.2),
(pg_temp.sid('food:Oats, dry'),'Oats, dry','40 g',40,389,16.9,66.3,6.9),
(pg_temp.sid('food:Quinoa, cooked'),'Quinoa, cooked','100 g',100,120,4.4,21.3,1.9),
(pg_temp.sid('food:Couscous, cooked'),'Couscous, cooked','100 g',100,112,3.8,23.2,0.2),
(pg_temp.sid('food:Potato, boiled'),'Potato, boiled','100 g',100,87,1.9,20,0.1),
(pg_temp.sid('food:Sweet potato, baked'),'Sweet potato, baked','100 g',100,90,2,20.7,0.2),
(pg_temp.sid('food:Wholemeal bread'),'Wholemeal bread','1 slice (36 g)',36,247,13,41,3.4),
(pg_temp.sid('food:White bread'),'White bread','1 slice (36 g)',36,265,9,49,3.2),
(pg_temp.sid('food:Sourdough bread'),'Sourdough bread','1 slice (50 g)',50,274,10.7,52,3.2),
(pg_temp.sid('food:Bagel, plain'),'Bagel, plain','1 bagel (90 g)',90,257,10,50,1.6),
(pg_temp.sid('food:Tortilla wrap'),'Tortilla wrap','1 wrap (62 g)',62,312,8.3,51.6,8),
(pg_temp.sid('food:Rice cakes'),'Rice cakes','1 cake (9 g)',9,387,8,81,2.8),
(pg_temp.sid('food:Granola'),'Granola','40 g',40,471,10,64,20),
(pg_temp.sid('food:Cornflakes'),'Cornflakes','30 g',30,357,7.5,84,0.4),
(pg_temp.sid('food:Banana'),'Banana','1 medium (118 g)',118,89,1.1,22.8,0.3),
(pg_temp.sid('food:Apple'),'Apple','1 medium (182 g)',182,52,0.3,13.8,0.2),
(pg_temp.sid('food:Blueberries'),'Blueberries','80 g',80,57,0.7,14.5,0.3),
(pg_temp.sid('food:Strawberries'),'Strawberries','80 g',80,32,0.7,7.7,0.3),
(pg_temp.sid('food:Raspberries'),'Raspberries','80 g',80,52,1.2,11.9,0.7),
(pg_temp.sid('food:Orange'),'Orange','1 medium (130 g)',130,47,0.9,11.8,0.1),
(pg_temp.sid('food:Mango'),'Mango','100 g',100,60,0.8,15,0.4),
(pg_temp.sid('food:Pineapple'),'Pineapple','100 g',100,50,0.5,13.1,0.1),
(pg_temp.sid('food:Grapes'),'Grapes','80 g',80,69,0.7,18.1,0.2),
(pg_temp.sid('food:Kiwi'),'Kiwi','1 fruit (75 g)',75,61,1.1,14.7,0.5),
(pg_temp.sid('food:Medjool dates'),'Medjool dates','1 date (24 g)',24,277,1.8,75,0.2),
(pg_temp.sid('food:Avocado'),'Avocado','half (75 g)',75,160,2,8.5,14.7),
(pg_temp.sid('food:Broccoli'),'Broccoli','80 g',80,34,2.8,6.6,0.4),
(pg_temp.sid('food:Spinach'),'Spinach','30 g',30,23,2.9,3.6,0.4),
(pg_temp.sid('food:Mixed salad leaves'),'Mixed salad leaves','30 g',30,15,1.4,2.9,0.2),
(pg_temp.sid('food:Tomato'),'Tomato','1 medium (120 g)',120,18,0.9,3.9,0.2),
(pg_temp.sid('food:Chopped tomatoes, canned'),'Chopped tomatoes, canned','200 g',200,21,1.2,3.5,0.2),
(pg_temp.sid('food:Cucumber'),'Cucumber','80 g',80,15,0.7,3.6,0.1),
(pg_temp.sid('food:Bell pepper'),'Bell pepper','1 pepper (150 g)',150,31,1,6,0.3),
(pg_temp.sid('food:Carrot'),'Carrot','1 medium (60 g)',60,41,0.9,9.6,0.2),
(pg_temp.sid('food:Onion'),'Onion','1 medium (110 g)',110,40,1.1,9.3,0.1),
(pg_temp.sid('food:Mushrooms'),'Mushrooms','80 g',80,22,3.1,3.3,0.3),
(pg_temp.sid('food:Courgette'),'Courgette','80 g',80,17,1.2,3.1,0.3),
(pg_temp.sid('food:Green beans'),'Green beans','80 g',80,31,1.8,7,0.2),
(pg_temp.sid('food:Asparagus'),'Asparagus','80 g',80,20,2.2,3.9,0.1),
(pg_temp.sid('food:Cauliflower'),'Cauliflower','80 g',80,25,1.9,5,0.3),
(pg_temp.sid('food:Kale'),'Kale','30 g',30,35,2.9,4.4,1.5),
(pg_temp.sid('food:Peas, frozen'),'Peas, frozen','80 g',80,81,5.4,14.5,0.4),
(pg_temp.sid('food:Sweetcorn'),'Sweetcorn','80 g',80,86,3.3,19,1.4),
(pg_temp.sid('food:Olive oil'),'Olive oil','1 tbsp (14 g)',14,884,0,0,100),
(pg_temp.sid('food:Butter'),'Butter','10 g',10,717,0.9,0.1,81),
(pg_temp.sid('food:Peanut butter'),'Peanut butter','1 tbsp (16 g)',16,588,25,20,50),
(pg_temp.sid('food:Almond butter'),'Almond butter','1 tbsp (16 g)',16,614,21,19,56),
(pg_temp.sid('food:Almonds'),'Almonds','30 g',30,579,21,22,50),
(pg_temp.sid('food:Walnuts'),'Walnuts','30 g',30,654,15,14,65),
(pg_temp.sid('food:Cashews'),'Cashews','30 g',30,553,18,30,44),
(pg_temp.sid('food:Peanuts'),'Peanuts','30 g',30,567,26,16,49),
(pg_temp.sid('food:Chia seeds'),'Chia seeds','1 tbsp (12 g)',12,486,17,42,31),
(pg_temp.sid('food:Ground flaxseed'),'Ground flaxseed','1 tbsp (10 g)',10,534,18,29,42),
(pg_temp.sid('food:Dark chocolate 70%'),'Dark chocolate 70%','20 g',20,598,7.8,46,43),
(pg_temp.sid('food:Hummus'),'Hummus','2 tbsp (60 g)',60,166,7.9,14.3,9.6),
(pg_temp.sid('food:Honey'),'Honey','1 tbsp (21 g)',21,304,0.3,82,0),
(pg_temp.sid('food:Maple syrup'),'Maple syrup','1 tbsp (20 g)',20,260,0,67,0.1),
(pg_temp.sid('food:Orange juice'),'Orange juice','250 ml glass',250,45,0.7,10.4,0.2),
(pg_temp.sid('food:Cola'),'Cola','330 ml can',330,42,0,10.6,0),
(pg_temp.sid('food:Lager beer'),'Lager beer','1 pint (568 ml)',568,43,0.5,3.6,0),
(pg_temp.sid('food:Red wine'),'Red wine','175 ml glass',175,85,0.1,2.6,0),
(pg_temp.sid('food:Latte, semi-skimmed'),'Latte, semi-skimmed','1 regular (300 ml)',300,50,3.3,4.9,1.9),
(pg_temp.sid('food:Pizza margherita'),'Pizza margherita','1 slice (100 g)',100,266,11,33,10),
(pg_temp.sid('food:Chips / fries'),'Chips / fries','1 portion (150 g)',150,312,3.4,41,15),
(pg_temp.sid('food:Crisps'),'Crisps','1 bag (25 g)',25,536,7,53,34)
on conflict (id) do nothing;

insert into public.recipes (id, name, meal_type, description, prep_min, kcal, protein, carbs, fat, ingredients, steps, tags) values
(pg_temp.sid('recipe:Protein overnight oats'),'Protein overnight oats','breakfast','Make it the night before and grab it in the morning.',5,540,43.2,67.4,12.7,array['60 g oats, dry','30 g whey protein powder','200 ml milk, semi-skimmed','80 g blueberries','10 g chia seeds']::text[],array['Stir oats, whey, chia and milk together in a jar.','Refrigerate overnight.','Top with blueberries before eating.']::text[],array['high protein','meal prep']::text[]),
(pg_temp.sid('recipe:Greek yogurt power bowl'),'Greek yogurt power bowl','breakfast','Fast, high protein and no cooking.',5,398,30.5,50.5,9.3,array['250 g Greek yogurt 0% fat','40 g granola','100 g strawberries','10 g honey']::text[],array['Spoon yogurt into a bowl.','Top with granola and sliced strawberries.','Drizzle with honey.']::text[],array['high protein','no cook']::text[]),
(pg_temp.sid('recipe:Veggie egg-white omelette'),'Veggie egg-white omelette','breakfast','Big volume, low calorie, plenty of protein.',12,357,39.6,24.1,11.1,array['200 g egg whites','50 g eggs, whole','50 g spinach','60 g mushrooms','50 g bell pepper','20 g feta','36 g wholemeal bread']::text[],array['Saute mushrooms and pepper in a non-stick pan.','Add spinach until wilted.','Pour in whisked egg whites and egg, cook until set.','Crumble feta on top, fold, and serve with toast.']::text[],array['high protein','low calorie']::text[]),
(pg_temp.sid('recipe:Banana protein pancakes'),'Banana protein pancakes','breakfast','Weekend pancakes that still fit your macros.',15,529,34.3,68.7,14.2,array['50 g oats, dry','118 g banana','100 g eggs, whole','15 g whey protein powder','10 g maple syrup']::text[],array['Blend oats, banana, eggs and whey into a batter.','Cook small pancakes in a non-stick pan, 2 minutes per side.','Serve with maple syrup.']::text[],array['high protein','sweet']::text[]),
(pg_temp.sid('recipe:Smoked salmon bagel'),'Smoked salmon bagel','breakfast','Omega-3s and protein in five minutes.',5,362,29.5,48.1,5.1,array['90 g bagel, plain','60 g cottage cheese, low fat','70 g smoked salmon','40 g cucumber']::text[],array['Toast the bagel.','Spread with cottage cheese.','Layer smoked salmon and sliced cucumber.']::text[],array['high protein','quick']::text[]),
(pg_temp.sid('recipe:Scrambled eggs on sourdough'),'Scrambled eggs on sourdough','breakfast','A classic with greens on the side.',10,466,28.3,42.0,20.9,array['150 g eggs, whole','70 g sourdough bread','5 g butter','40 g spinach','80 g tomato']::text[],array['Whisk eggs and scramble gently in butter.','Wilt spinach in the same pan.','Serve on toasted sourdough with sliced tomato.']::text[],array['vegetarian','quick']::text[]),
(pg_temp.sid('recipe:Chicken burrito bowl'),'Chicken burrito bowl','lunch','Meal-prep friendly and easy to scale.',15,686,61.3,77.9,14.5,array['150 g chicken breast, cooked','150 g white rice, cooked','80 g black beans, cooked','50 g sweetcorn','60 g tomato','50 g avocado','30 g mixed salad leaves']::text[],array['Slice the cooked chicken.','Build the bowl on rice with beans, corn, tomato and leaves.','Top with sliced avocado.']::text[],array['high protein','meal prep']::text[]),
(pg_temp.sid('recipe:Tuna and chickpea salad'),'Tuna and chickpea salad','lunch','No cooking, packs well for work.',10,542,47.7,42.9,20.9,array['120 g tuna, canned in water, drained','120 g chickpeas, cooked','80 g cucumber','80 g tomato','30 g onion','10 g olive oil','30 g feta']::text[],array['Drain the tuna and chickpeas.','Chop cucumber, tomato and onion.','Toss everything with olive oil and crumbled feta.']::text[],array['high protein','no cook']::text[]),
(pg_temp.sid('recipe:Turkey and hummus wrap'),'Turkey and hummus wrap','lunch','Lunch in five minutes.',5,417,39.7,41.8,10.1,array['62 g tortilla wrap','100 g turkey breast, cooked','40 g hummus','30 g spinach','50 g bell pepper']::text[],array['Spread hummus over the wrap.','Add turkey, spinach and sliced pepper.','Roll tightly and cut in half.']::text[],array['quick','high protein']::text[]),
(pg_temp.sid('recipe:Quinoa and halloumi salad'),'Quinoa and halloumi salad','lunch','Vegetarian lunch with a salty crunch.',15,464,21.5,40.0,25.2,array['150 g quinoa, cooked','60 g halloumi','40 g spinach','80 g tomato','60 g cucumber','7 g olive oil']::text[],array['Grill halloumi slices until golden.','Toss quinoa with spinach, tomato and cucumber.','Top with halloumi and drizzle with oil.']::text[],array['vegetarian']::text[]),
(pg_temp.sid('recipe:Prawn noodle stir-fry'),'Prawn noodle stir-fry','lunch','Quick wok dish with plenty of veg.',15,525,47.4,59.0,11.8,array['150 g prawns, cooked','180 g egg noodles, cooked','80 g broccoli','60 g bell pepper','50 g carrot','7 g olive oil']::text[],array['Stir-fry broccoli, pepper and carrot in oil for 3 minutes.','Add prawns and noodles, toss until hot.','Season with soy sauce and chilli to taste.']::text[],array['high protein','quick']::text[]),
(pg_temp.sid('recipe:Lentil and vegetable soup'),'Lentil and vegetable soup','lunch','Batch-cook for the week.',30,456,26.7,73.7,7.6,array['200 g lentils, cooked','80 g carrot','60 g onion','120 g chopped tomatoes, canned','40 g spinach','5 g olive oil','36 g wholemeal bread']::text[],array['Soften onion and carrot in oil.','Add tomatoes, lentils and stock, simmer 20 minutes.','Stir in spinach and serve with bread.']::text[],array['vegan','meal prep','high fibre']::text[]),
(pg_temp.sid('recipe:Salmon, sweet potato and greens'),'Salmon, sweet potato and greens','dinner','Balanced plate for recovery days.',25,547,37.6,48.0,22.6,array['140 g salmon fillet, cooked','200 g sweet potato, baked','100 g broccoli','5 g olive oil']::text[],array['Bake sweet potato wedges at 200C for 25 minutes.','Roast salmon for the last 12 minutes.','Steam broccoli and drizzle with oil.']::text[],array['high protein','omega-3']::text[]),
(pg_temp.sid('recipe:Lean beef bolognese'),'Lean beef bolognese','dinner','Family favourite with lean mince.',30,647,57.4,68.1,15.6,array['150 g beef mince 5% fat, cooked','180 g pasta, cooked','150 g chopped tomatoes, canned','50 g onion','60 g mushrooms','10 g parmesan']::text[],array['Brown the mince with onion and mushrooms.','Add tomatoes and simmer 20 minutes.','Serve over pasta with grated parmesan.']::text[],array['high protein','meal prep']::text[]),
(pg_temp.sid('recipe:Chicken thigh tray bake'),'Chicken thigh tray bake','dinner','One tray, minimal washing up.',40,670,52.9,51.9,27.3,array['180 g chicken thigh, cooked, skinless','200 g potato, boiled','80 g bell pepper','80 g courgette','50 g onion','7 g olive oil']::text[],array['Chop potatoes and veg, toss with oil and seasoning.','Add chicken thighs and roast at 200C for 35 minutes.']::text[],array['high protein','one pan']::text[]),
(pg_temp.sid('recipe:Steak, rice and asparagus'),'Steak, rice and asparagus','dinner','Simple, high protein dinner.',20,601,57.3,45.9,19.9,array['170 g sirloin steak, cooked','150 g white rice, cooked','100 g asparagus','5 g butter']::text[],array['Sear steak 3 minutes per side, rest 5 minutes.','Pan-fry asparagus in butter.','Serve with rice.']::text[],array['high protein']::text[]),
(pg_temp.sid('recipe:Lemon cod with couscous'),'Lemon cod with couscous','dinner','Light and fresh, high protein.',20,491,52.9,52.0,7.4,array['180 g cod, cooked','150 g couscous, cooked','80 g peas, frozen','80 g green beans','5 g olive oil']::text[],array['Bake cod with lemon for 12 minutes.','Fluff couscous with peas.','Serve with green beans and a drizzle of oil.']::text[],array['high protein','low fat']::text[]),
(pg_temp.sid('recipe:Tofu satay stir-fry'),'Tofu satay stir-fry','dinner','Plant-based dinner with a peanut kick.',20,620,44.1,57.9,27.1,array['200 g tofu, firm','150 g brown rice, cooked','80 g broccoli','60 g bell pepper','60 g mushrooms','15 g peanut butter']::text[],array['Press and cube tofu, pan-fry until golden.','Stir-fry the vegetables.','Loosen peanut butter with water and soy, toss through, serve on rice.']::text[],array['vegan','high protein']::text[]),
(pg_temp.sid('recipe:Turkey chilli'),'Turkey chilli','dinner','Freezer-friendly chilli.',35,595,60.7,78.3,3.0,array['150 g turkey breast, cooked','100 g kidney beans, cooked','150 g chopped tomatoes, canned','50 g onion','60 g bell pepper','150 g white rice, cooked']::text[],array['Soften onion and pepper.','Add turkey, beans, tomatoes and chilli spices, simmer 25 minutes.','Serve over rice.']::text[],array['high protein','meal prep']::text[]),
(pg_temp.sid('recipe:Chickpea and spinach curry'),'Chickpea and spinach curry','dinner','Creamy vegetarian curry.',25,690,31.1,112.5,13.8,array['200 g chickpeas, cooked','80 g spinach','150 g chopped tomatoes, canned','60 g onion','50 g Greek yogurt, full fat','150 g white rice, cooked','5 g olive oil']::text[],array['Fry onion with curry spices in oil.','Add tomatoes and chickpeas, simmer 15 minutes.','Stir in spinach and yogurt, serve with rice.']::text[],array['vegetarian','high fibre']::text[]),
(pg_temp.sid('recipe:Cottage cheese and pineapple'),'Cottage cheese and pineapple','snack','Sweet, high protein snack.',2,194,25.3,18.5,2.1,array['200 g cottage cheese, low fat','100 g pineapple']::text[],array['Top cottage cheese with pineapple chunks.']::text[],array['high protein','no cook']::text[]),
(pg_temp.sid('recipe:Apple and peanut butter'),'Apple and peanut butter','snack','Classic pre-workout snack.',2,212,5.5,29.1,10.4,array['182 g apple','20 g peanut butter']::text[],array['Slice the apple and dip in peanut butter.']::text[],array['quick']::text[]),
(pg_temp.sid('recipe:Protein shake and banana'),'Protein shake and banana','snack','Post-workout in under a minute.',2,363,35.5,43.4,7.3,array['30 g whey protein powder','300 ml milk, semi-skimmed','118 g banana']::text[],array['Shake whey with milk.','Have the banana alongside.']::text[],array['high protein','post-workout']::text[]),
(pg_temp.sid('recipe:Rice cakes with almond butter'),'Rice cakes with almond butter','snack','Crunchy and quick.',3,216,5.7,29.3,9.3,array['27 g rice cakes','15 g almond butter','60 g strawberries']::text[],array['Spread almond butter on rice cakes and top with sliced strawberries.']::text[],array['quick']::text[]),
(pg_temp.sid('recipe:Skyr with berries and almonds'),'Skyr with berries and almonds','snack','High protein, high fibre.',3,236,22.8,19.6,8.4,array['170 g skyr, plain','80 g raspberries','15 g almonds']::text[],array['Top skyr with raspberries and chopped almonds.']::text[],array['high protein','no cook']::text[]),
(pg_temp.sid('recipe:Hummus and veg sticks'),'Hummus and veg sticks','snack','Crunchy, plant-based snack.',5,163,6.6,22.7,6.2,array['60 g hummus','80 g carrot','80 g cucumber','60 g bell pepper']::text[],array['Cut veg into sticks and serve with hummus.']::text[],array['vegan','no cook']::text[]),
(pg_temp.sid('recipe:Boiled eggs and edamame'),'Boiled eggs and edamame','snack','Savoury protein snack.',10,264,24.5,9.6,14.7,array['100 g eggs, whole','100 g edamame']::text[],array['Boil eggs for 8 minutes.','Steam edamame and season with salt.']::text[],array['high protein']::text[]),
(pg_temp.sid('recipe:Dark chocolate and almonds'),'Dark chocolate and almonds','snack','A sweet treat that fits.',1,235,5.8,13.6,18.6,array['20 g dark chocolate 70%','20 g almonds']::text[],array['Enjoy slowly.']::text[],array['sweet']::text[])
on conflict (id) do nothing;

insert into public.workouts (id, name, format, duration_min, rounds, description) values
(pg_temp.sid('w:fb_a'),'Full body A','standard',50,null,'Beginner full-body session built on the main movement patterns.'),
(pg_temp.sid('w:fb_b'),'Full body B','standard',50,null,'Second beginner full-body session to alternate with A.'),
(pg_temp.sid('w:push'),'Push','standard',60,null,'Chest, shoulders and triceps.'),
(pg_temp.sid('w:pull'),'Pull','standard',60,null,'Back, rear delts and biceps.'),
(pg_temp.sid('w:legs'),'Legs','standard',65,null,'Quads, hamstrings, glutes and calves.'),
(pg_temp.sid('w:upper'),'Upper strength','standard',60,null,'Heavy upper-body compounds.'),
(pg_temp.sid('w:lower'),'Lower strength','standard',60,null,'Heavy lower-body compounds.'),
(pg_temp.sid('w:fxf_a'),'5x5 A','standard',55,null,'Classic linear strength day A.'),
(pg_temp.sid('w:fxf_b'),'5x5 B','standard',55,null,'Classic linear strength day B.'),
(pg_temp.sid('w:metcon'),'Metcon circuit','circuit',30,4,'4 rounds, move between exercises with minimal rest, 90 s between rounds.'),
(pg_temp.sid('w:amrap20'),'20-minute AMRAP','amrap',20,null,'As many rounds as possible in 20 minutes. Log your rounds.'),
(pg_temp.sid('w:emom16'),'EMOM 16','emom',16,null,'Every minute on the minute, rotate through the four stations.'),
(pg_temp.sid('w:home'),'Home bodyweight','standard',35,null,'No equipment needed.'),
(pg_temp.sid('w:mobility'),'Mobility flow','standard',20,null,'Recovery-day mobility, move slowly and breathe.'),
(pg_temp.sid('w:intervals'),'Treadmill intervals','intervals',25,null,'Warm up 5 minutes, then 8 rounds of 1 minute hard, 1 minute easy.'),
(pg_temp.sid('w:core'),'Core finisher','standard',15,null,'Short core session to add after any workout.')
on conflict (id) do nothing;

insert into public.workout_items (id, workout_id, exercise_id, exercise_name, sort, group_label, sets, reps, percent_1rm, rest_sec, notes) values
(pg_temp.sid('wi:fb_a:0'),pg_temp.sid('w:fb_a'),pg_temp.sid('ex:Goblet squat'),'Goblet squat',0,'',3,'10',null,90,''),
(pg_temp.sid('wi:fb_a:1'),pg_temp.sid('w:fb_a'),pg_temp.sid('ex:Dumbbell bench press'),'Dumbbell bench press',1,'',3,'10',null,90,''),
(pg_temp.sid('wi:fb_a:2'),pg_temp.sid('w:fb_a'),pg_temp.sid('ex:Seated cable row'),'Seated cable row',2,'',3,'12',null,90,''),
(pg_temp.sid('wi:fb_a:3'),pg_temp.sid('w:fb_a'),pg_temp.sid('ex:Romanian deadlift'),'Romanian deadlift',3,'',3,'10',null,90,''),
(pg_temp.sid('wi:fb_a:4'),pg_temp.sid('w:fb_a'),pg_temp.sid('ex:Plank'),'Plank',4,'',3,'30 s',null,60,''),
(pg_temp.sid('wi:fb_b:0'),pg_temp.sid('w:fb_b'),pg_temp.sid('ex:Leg press'),'Leg press',0,'',3,'12',null,90,''),
(pg_temp.sid('wi:fb_b:1'),pg_temp.sid('w:fb_b'),pg_temp.sid('ex:Lat pulldown'),'Lat pulldown',1,'',3,'10',null,90,''),
(pg_temp.sid('wi:fb_b:2'),pg_temp.sid('w:fb_b'),pg_temp.sid('ex:Seated dumbbell shoulder press'),'Seated dumbbell shoulder press',2,'',3,'10',null,90,''),
(pg_temp.sid('wi:fb_b:3'),pg_temp.sid('w:fb_b'),pg_temp.sid('ex:Glute bridge'),'Glute bridge',3,'',3,'12',null,60,''),
(pg_temp.sid('wi:fb_b:4'),pg_temp.sid('w:fb_b'),pg_temp.sid('ex:Dead bug'),'Dead bug',4,'',3,'10 per side',null,45,''),
(pg_temp.sid('wi:push:0'),pg_temp.sid('w:push'),pg_temp.sid('ex:Barbell bench press'),'Barbell bench press',0,'',4,'6-8',75,150,'Last set: 1-2 reps in reserve'),
(pg_temp.sid('wi:push:1'),pg_temp.sid('w:push'),pg_temp.sid('ex:Incline dumbbell press'),'Incline dumbbell press',1,'',3,'10',null,90,''),
(pg_temp.sid('wi:push:2'),pg_temp.sid('w:push'),pg_temp.sid('ex:Overhead press'),'Overhead press',2,'',3,'8',null,120,''),
(pg_temp.sid('wi:push:3'),pg_temp.sid('w:push'),pg_temp.sid('ex:Lateral raise'),'Lateral raise',3,'',3,'15',null,60,''),
(pg_temp.sid('wi:push:4'),pg_temp.sid('w:push'),pg_temp.sid('ex:Triceps pushdown'),'Triceps pushdown',4,'A',3,'12',null,0,'Superset with A2'),
(pg_temp.sid('wi:push:5'),pg_temp.sid('w:push'),pg_temp.sid('ex:Overhead triceps extension'),'Overhead triceps extension',5,'A',3,'12',null,75,''),
(pg_temp.sid('wi:pull:0'),pg_temp.sid('w:pull'),pg_temp.sid('ex:Deadlift'),'Deadlift',0,'',3,'5',80,180,''),
(pg_temp.sid('wi:pull:1'),pg_temp.sid('w:pull'),pg_temp.sid('ex:Pull-up'),'Pull-up',1,'',4,'max',null,120,'Use a band if needed'),
(pg_temp.sid('wi:pull:2'),pg_temp.sid('w:pull'),pg_temp.sid('ex:Barbell row'),'Barbell row',2,'',3,'8',null,90,''),
(pg_temp.sid('wi:pull:3'),pg_temp.sid('w:pull'),pg_temp.sid('ex:Face pull'),'Face pull',3,'',3,'15',null,60,''),
(pg_temp.sid('wi:pull:4'),pg_temp.sid('w:pull'),pg_temp.sid('ex:Hammer curl'),'Hammer curl',4,'A',3,'12',null,0,'Superset with A2'),
(pg_temp.sid('wi:pull:5'),pg_temp.sid('w:pull'),pg_temp.sid('ex:Barbell curl'),'Barbell curl',5,'A',3,'10',null,75,''),
(pg_temp.sid('wi:legs:0'),pg_temp.sid('w:legs'),pg_temp.sid('ex:Back squat'),'Back squat',0,'',4,'6',75,180,''),
(pg_temp.sid('wi:legs:1'),pg_temp.sid('w:legs'),pg_temp.sid('ex:Romanian deadlift'),'Romanian deadlift',1,'',3,'8',null,120,''),
(pg_temp.sid('wi:legs:2'),pg_temp.sid('w:legs'),pg_temp.sid('ex:Bulgarian split squat'),'Bulgarian split squat',2,'',3,'10 per leg',null,90,''),
(pg_temp.sid('wi:legs:3'),pg_temp.sid('w:legs'),pg_temp.sid('ex:Lying leg curl'),'Lying leg curl',3,'',3,'12',null,60,''),
(pg_temp.sid('wi:legs:4'),pg_temp.sid('w:legs'),pg_temp.sid('ex:Standing calf raise'),'Standing calf raise',4,'',4,'15',null,45,''),
(pg_temp.sid('wi:upper:0'),pg_temp.sid('w:upper'),pg_temp.sid('ex:Barbell bench press'),'Barbell bench press',0,'',5,'5',80,180,''),
(pg_temp.sid('wi:upper:1'),pg_temp.sid('w:upper'),pg_temp.sid('ex:Barbell row'),'Barbell row',1,'',5,'5',null,150,''),
(pg_temp.sid('wi:upper:2'),pg_temp.sid('w:upper'),pg_temp.sid('ex:Overhead press'),'Overhead press',2,'',3,'8',null,120,''),
(pg_temp.sid('wi:upper:3'),pg_temp.sid('w:upper'),pg_temp.sid('ex:Chin-up'),'Chin-up',3,'',3,'8',null,90,''),
(pg_temp.sid('wi:upper:4'),pg_temp.sid('w:upper'),pg_temp.sid('ex:Dips'),'Dips',4,'',3,'max',null,90,''),
(pg_temp.sid('wi:lower:0'),pg_temp.sid('w:lower'),pg_temp.sid('ex:Back squat'),'Back squat',0,'',5,'5',80,180,''),
(pg_temp.sid('wi:lower:1'),pg_temp.sid('w:lower'),pg_temp.sid('ex:Romanian deadlift'),'Romanian deadlift',1,'',3,'8',null,120,''),
(pg_temp.sid('wi:lower:2'),pg_temp.sid('w:lower'),pg_temp.sid('ex:Walking lunge'),'Walking lunge',2,'',3,'12 per leg',null,90,''),
(pg_temp.sid('wi:lower:3'),pg_temp.sid('w:lower'),pg_temp.sid('ex:Hip thrust'),'Hip thrust',3,'',3,'10',null,90,''),
(pg_temp.sid('wi:lower:4'),pg_temp.sid('w:lower'),pg_temp.sid('ex:Hanging leg raise'),'Hanging leg raise',4,'',3,'12',null,60,''),
(pg_temp.sid('wi:fxf_a:0'),pg_temp.sid('w:fxf_a'),pg_temp.sid('ex:Back squat'),'Back squat',0,'',5,'5',80,180,''),
(pg_temp.sid('wi:fxf_a:1'),pg_temp.sid('w:fxf_a'),pg_temp.sid('ex:Barbell bench press'),'Barbell bench press',1,'',5,'5',80,180,''),
(pg_temp.sid('wi:fxf_a:2'),pg_temp.sid('w:fxf_a'),pg_temp.sid('ex:Barbell row'),'Barbell row',2,'',5,'5',null,150,''),
(pg_temp.sid('wi:fxf_b:0'),pg_temp.sid('w:fxf_b'),pg_temp.sid('ex:Back squat'),'Back squat',0,'',5,'5',80,180,''),
(pg_temp.sid('wi:fxf_b:1'),pg_temp.sid('w:fxf_b'),pg_temp.sid('ex:Overhead press'),'Overhead press',1,'',5,'5',80,180,''),
(pg_temp.sid('wi:fxf_b:2'),pg_temp.sid('w:fxf_b'),pg_temp.sid('ex:Deadlift'),'Deadlift',2,'',1,'5',85,0,''),
(pg_temp.sid('wi:metcon:0'),pg_temp.sid('w:metcon'),pg_temp.sid('ex:Kettlebell swing'),'Kettlebell swing',0,'A',null,'15',null,0,''),
(pg_temp.sid('wi:metcon:1'),pg_temp.sid('w:metcon'),pg_temp.sid('ex:Push-up'),'Push-up',1,'A',null,'12',null,0,''),
(pg_temp.sid('wi:metcon:2'),pg_temp.sid('w:metcon'),pg_temp.sid('ex:Jump squat'),'Jump squat',2,'A',null,'12',null,0,''),
(pg_temp.sid('wi:metcon:3'),pg_temp.sid('w:metcon'),pg_temp.sid('ex:Mountain climber'),'Mountain climber',3,'A',null,'30 s',null,0,''),
(pg_temp.sid('wi:metcon:4'),pg_temp.sid('w:metcon'),pg_temp.sid('ex:Rowing machine'),'Rowing machine',4,'A',null,'250 m',null,90,'Rest after the row'),
(pg_temp.sid('wi:amrap20:0'),pg_temp.sid('w:amrap20'),pg_temp.sid('ex:Burpee'),'Burpee',0,'A',null,'10',null,0,''),
(pg_temp.sid('wi:amrap20:1'),pg_temp.sid('w:amrap20'),pg_temp.sid('ex:Goblet squat'),'Goblet squat',1,'A',null,'15',null,0,''),
(pg_temp.sid('wi:amrap20:2'),pg_temp.sid('w:amrap20'),pg_temp.sid('ex:Medicine ball slam'),'Medicine ball slam',2,'A',null,'12',null,0,''),
(pg_temp.sid('wi:amrap20:3'),pg_temp.sid('w:amrap20'),pg_temp.sid('ex:Assault bike'),'Assault bike',3,'A',null,'12 cal',null,0,''),
(pg_temp.sid('wi:emom16:0'),pg_temp.sid('w:emom16'),pg_temp.sid('ex:Kettlebell swing'),'Kettlebell swing',0,'A',null,'15',null,0,'Minute 1'),
(pg_temp.sid('wi:emom16:1'),pg_temp.sid('w:emom16'),pg_temp.sid('ex:Push-up'),'Push-up',1,'A',null,'12',null,0,'Minute 2'),
(pg_temp.sid('wi:emom16:2'),pg_temp.sid('w:emom16'),pg_temp.sid('ex:Box jump'),'Box jump',2,'A',null,'10',null,0,'Minute 3'),
(pg_temp.sid('wi:emom16:3'),pg_temp.sid('w:emom16'),pg_temp.sid('ex:Plank'),'Plank',3,'A',null,'40 s',null,0,'Minute 4'),
(pg_temp.sid('wi:home:0'),pg_temp.sid('w:home'),pg_temp.sid('ex:Push-up'),'Push-up',0,'',4,'12',null,60,''),
(pg_temp.sid('wi:home:1'),pg_temp.sid('w:home'),pg_temp.sid('ex:Reverse lunge'),'Reverse lunge',1,'',3,'10 per leg',null,60,''),
(pg_temp.sid('wi:home:2'),pg_temp.sid('w:home'),pg_temp.sid('ex:Glute bridge'),'Glute bridge',2,'',3,'15',null,45,''),
(pg_temp.sid('wi:home:3'),pg_temp.sid('w:home'),pg_temp.sid('ex:Burpee'),'Burpee',3,'',3,'10',null,60,''),
(pg_temp.sid('wi:home:4'),pg_temp.sid('w:home'),pg_temp.sid('ex:Plank'),'Plank',4,'',3,'40 s',null,45,''),
(pg_temp.sid('wi:home:5'),pg_temp.sid('w:home'),pg_temp.sid('ex:Mountain climber'),'Mountain climber',5,'',3,'30 s',null,45,''),
(pg_temp.sid('wi:mobility:0'),pg_temp.sid('w:mobility'),pg_temp.sid('ex:World''s greatest stretch'),'World''s greatest stretch',0,'',2,'5 per side',null,0,''),
(pg_temp.sid('wi:mobility:1'),pg_temp.sid('w:mobility'),pg_temp.sid('ex:Hip 90/90'),'Hip 90/90',1,'',2,'8',null,0,''),
(pg_temp.sid('wi:mobility:2'),pg_temp.sid('w:mobility'),pg_temp.sid('ex:Cat-cow'),'Cat-cow',2,'',2,'10',null,0,''),
(pg_temp.sid('wi:mobility:3'),pg_temp.sid('w:mobility'),pg_temp.sid('ex:Thoracic rotation'),'Thoracic rotation',3,'',2,'8 per side',null,0,''),
(pg_temp.sid('wi:mobility:4'),pg_temp.sid('w:mobility'),pg_temp.sid('ex:Couch stretch'),'Couch stretch',4,'',2,'45 s per side',null,0,''),
(pg_temp.sid('wi:mobility:5'),pg_temp.sid('w:mobility'),pg_temp.sid('ex:Deep squat hold'),'Deep squat hold',5,'',2,'60 s',null,0,''),
(pg_temp.sid('wi:intervals:0'),pg_temp.sid('w:intervals'),pg_temp.sid('ex:Treadmill run'),'Treadmill run',0,'',8,'60 s hard / 60 s easy',null,0,'Hard = 8/10 effort'),
(pg_temp.sid('wi:core:0'),pg_temp.sid('w:core'),pg_temp.sid('ex:Ab wheel rollout'),'Ab wheel rollout',0,'',3,'10',null,45,''),
(pg_temp.sid('wi:core:1'),pg_temp.sid('w:core'),pg_temp.sid('ex:Pallof press'),'Pallof press',1,'',3,'12 per side',null,45,''),
(pg_temp.sid('wi:core:2'),pg_temp.sid('w:core'),pg_temp.sid('ex:Hollow hold'),'Hollow hold',2,'',3,'30 s',null,45,''),
(pg_temp.sid('wi:core:3'),pg_temp.sid('w:core'),pg_temp.sid('ex:Side plank'),'Side plank',3,'',3,'30 s per side',null,45,'')
on conflict (id) do nothing;

insert into public.programs (id, name, goal, level, weeks, description) values
(pg_temp.sid('p:beginner'),'Beginner full body','General fitness','Beginner',4,'Three full-body sessions a week alternating A and B.'),
(pg_temp.sid('p:ppl'),'Push pull legs','Muscle gain','Intermediate',6,'Six days a week, each muscle group twice.'),
(pg_temp.sid('p:upper_lower'),'Upper / lower strength','Strength','Intermediate',8,'Four heavy days a week.'),
(pg_temp.sid('p:five_by_five'),'Classic 5x5','Strength','Beginner',8,'Three days a week alternating A and B with steady load increases.'),
(pg_temp.sid('p:fat_loss'),'Fat loss conditioning','Fat loss','All levels',4,'Strength plus conditioning and a mobility day.'),
(pg_temp.sid('p:home'),'Home training','General fitness','All levels',4,'No-equipment plan with a mobility day.')
on conflict (id) do nothing;

insert into public.program_days (id, program_id, week, day, workout_id) values
(pg_temp.sid('pd:beginner:1:1:fb_a'),pg_temp.sid('p:beginner'),1,1,pg_temp.sid('w:fb_a')),
(pg_temp.sid('pd:beginner:1:3:fb_b'),pg_temp.sid('p:beginner'),1,3,pg_temp.sid('w:fb_b')),
(pg_temp.sid('pd:beginner:1:5:fb_a'),pg_temp.sid('p:beginner'),1,5,pg_temp.sid('w:fb_a')),
(pg_temp.sid('pd:beginner:2:1:fb_b'),pg_temp.sid('p:beginner'),2,1,pg_temp.sid('w:fb_b')),
(pg_temp.sid('pd:beginner:2:3:fb_a'),pg_temp.sid('p:beginner'),2,3,pg_temp.sid('w:fb_a')),
(pg_temp.sid('pd:beginner:2:5:fb_b'),pg_temp.sid('p:beginner'),2,5,pg_temp.sid('w:fb_b')),
(pg_temp.sid('pd:beginner:3:1:fb_a'),pg_temp.sid('p:beginner'),3,1,pg_temp.sid('w:fb_a')),
(pg_temp.sid('pd:beginner:3:3:fb_b'),pg_temp.sid('p:beginner'),3,3,pg_temp.sid('w:fb_b')),
(pg_temp.sid('pd:beginner:3:5:fb_a'),pg_temp.sid('p:beginner'),3,5,pg_temp.sid('w:fb_a')),
(pg_temp.sid('pd:beginner:4:1:fb_b'),pg_temp.sid('p:beginner'),4,1,pg_temp.sid('w:fb_b')),
(pg_temp.sid('pd:beginner:4:3:fb_a'),pg_temp.sid('p:beginner'),4,3,pg_temp.sid('w:fb_a')),
(pg_temp.sid('pd:beginner:4:5:fb_b'),pg_temp.sid('p:beginner'),4,5,pg_temp.sid('w:fb_b')),
(pg_temp.sid('pd:ppl:1:1:push'),pg_temp.sid('p:ppl'),1,1,pg_temp.sid('w:push')),
(pg_temp.sid('pd:ppl:1:2:pull'),pg_temp.sid('p:ppl'),1,2,pg_temp.sid('w:pull')),
(pg_temp.sid('pd:ppl:1:3:legs'),pg_temp.sid('p:ppl'),1,3,pg_temp.sid('w:legs')),
(pg_temp.sid('pd:ppl:1:4:push'),pg_temp.sid('p:ppl'),1,4,pg_temp.sid('w:push')),
(pg_temp.sid('pd:ppl:1:5:pull'),pg_temp.sid('p:ppl'),1,5,pg_temp.sid('w:pull')),
(pg_temp.sid('pd:ppl:1:6:legs'),pg_temp.sid('p:ppl'),1,6,pg_temp.sid('w:legs')),
(pg_temp.sid('pd:ppl:2:1:push'),pg_temp.sid('p:ppl'),2,1,pg_temp.sid('w:push')),
(pg_temp.sid('pd:ppl:2:2:pull'),pg_temp.sid('p:ppl'),2,2,pg_temp.sid('w:pull')),
(pg_temp.sid('pd:ppl:2:3:legs'),pg_temp.sid('p:ppl'),2,3,pg_temp.sid('w:legs')),
(pg_temp.sid('pd:ppl:2:4:push'),pg_temp.sid('p:ppl'),2,4,pg_temp.sid('w:push')),
(pg_temp.sid('pd:ppl:2:5:pull'),pg_temp.sid('p:ppl'),2,5,pg_temp.sid('w:pull')),
(pg_temp.sid('pd:ppl:2:6:legs'),pg_temp.sid('p:ppl'),2,6,pg_temp.sid('w:legs')),
(pg_temp.sid('pd:ppl:3:1:push'),pg_temp.sid('p:ppl'),3,1,pg_temp.sid('w:push')),
(pg_temp.sid('pd:ppl:3:2:pull'),pg_temp.sid('p:ppl'),3,2,pg_temp.sid('w:pull')),
(pg_temp.sid('pd:ppl:3:3:legs'),pg_temp.sid('p:ppl'),3,3,pg_temp.sid('w:legs')),
(pg_temp.sid('pd:ppl:3:4:push'),pg_temp.sid('p:ppl'),3,4,pg_temp.sid('w:push')),
(pg_temp.sid('pd:ppl:3:5:pull'),pg_temp.sid('p:ppl'),3,5,pg_temp.sid('w:pull')),
(pg_temp.sid('pd:ppl:3:6:legs'),pg_temp.sid('p:ppl'),3,6,pg_temp.sid('w:legs')),
(pg_temp.sid('pd:ppl:4:1:push'),pg_temp.sid('p:ppl'),4,1,pg_temp.sid('w:push')),
(pg_temp.sid('pd:ppl:4:2:pull'),pg_temp.sid('p:ppl'),4,2,pg_temp.sid('w:pull')),
(pg_temp.sid('pd:ppl:4:3:legs'),pg_temp.sid('p:ppl'),4,3,pg_temp.sid('w:legs')),
(pg_temp.sid('pd:ppl:4:4:push'),pg_temp.sid('p:ppl'),4,4,pg_temp.sid('w:push')),
(pg_temp.sid('pd:ppl:4:5:pull'),pg_temp.sid('p:ppl'),4,5,pg_temp.sid('w:pull')),
(pg_temp.sid('pd:ppl:4:6:legs'),pg_temp.sid('p:ppl'),4,6,pg_temp.sid('w:legs')),
(pg_temp.sid('pd:ppl:5:1:push'),pg_temp.sid('p:ppl'),5,1,pg_temp.sid('w:push')),
(pg_temp.sid('pd:ppl:5:2:pull'),pg_temp.sid('p:ppl'),5,2,pg_temp.sid('w:pull')),
(pg_temp.sid('pd:ppl:5:3:legs'),pg_temp.sid('p:ppl'),5,3,pg_temp.sid('w:legs')),
(pg_temp.sid('pd:ppl:5:4:push'),pg_temp.sid('p:ppl'),5,4,pg_temp.sid('w:push')),
(pg_temp.sid('pd:ppl:5:5:pull'),pg_temp.sid('p:ppl'),5,5,pg_temp.sid('w:pull')),
(pg_temp.sid('pd:ppl:5:6:legs'),pg_temp.sid('p:ppl'),5,6,pg_temp.sid('w:legs')),
(pg_temp.sid('pd:ppl:6:1:push'),pg_temp.sid('p:ppl'),6,1,pg_temp.sid('w:push')),
(pg_temp.sid('pd:ppl:6:2:pull'),pg_temp.sid('p:ppl'),6,2,pg_temp.sid('w:pull')),
(pg_temp.sid('pd:ppl:6:3:legs'),pg_temp.sid('p:ppl'),6,3,pg_temp.sid('w:legs')),
(pg_temp.sid('pd:ppl:6:4:push'),pg_temp.sid('p:ppl'),6,4,pg_temp.sid('w:push')),
(pg_temp.sid('pd:ppl:6:5:pull'),pg_temp.sid('p:ppl'),6,5,pg_temp.sid('w:pull')),
(pg_temp.sid('pd:ppl:6:6:legs'),pg_temp.sid('p:ppl'),6,6,pg_temp.sid('w:legs')),
(pg_temp.sid('pd:upper_lower:1:1:upper'),pg_temp.sid('p:upper_lower'),1,1,pg_temp.sid('w:upper')),
(pg_temp.sid('pd:upper_lower:1:2:lower'),pg_temp.sid('p:upper_lower'),1,2,pg_temp.sid('w:lower')),
(pg_temp.sid('pd:upper_lower:1:4:upper'),pg_temp.sid('p:upper_lower'),1,4,pg_temp.sid('w:upper')),
(pg_temp.sid('pd:upper_lower:1:5:lower'),pg_temp.sid('p:upper_lower'),1,5,pg_temp.sid('w:lower')),
(pg_temp.sid('pd:upper_lower:2:1:upper'),pg_temp.sid('p:upper_lower'),2,1,pg_temp.sid('w:upper')),
(pg_temp.sid('pd:upper_lower:2:2:lower'),pg_temp.sid('p:upper_lower'),2,2,pg_temp.sid('w:lower')),
(pg_temp.sid('pd:upper_lower:2:4:upper'),pg_temp.sid('p:upper_lower'),2,4,pg_temp.sid('w:upper')),
(pg_temp.sid('pd:upper_lower:2:5:lower'),pg_temp.sid('p:upper_lower'),2,5,pg_temp.sid('w:lower')),
(pg_temp.sid('pd:upper_lower:3:1:upper'),pg_temp.sid('p:upper_lower'),3,1,pg_temp.sid('w:upper')),
(pg_temp.sid('pd:upper_lower:3:2:lower'),pg_temp.sid('p:upper_lower'),3,2,pg_temp.sid('w:lower')),
(pg_temp.sid('pd:upper_lower:3:4:upper'),pg_temp.sid('p:upper_lower'),3,4,pg_temp.sid('w:upper')),
(pg_temp.sid('pd:upper_lower:3:5:lower'),pg_temp.sid('p:upper_lower'),3,5,pg_temp.sid('w:lower')),
(pg_temp.sid('pd:upper_lower:4:1:upper'),pg_temp.sid('p:upper_lower'),4,1,pg_temp.sid('w:upper')),
(pg_temp.sid('pd:upper_lower:4:2:lower'),pg_temp.sid('p:upper_lower'),4,2,pg_temp.sid('w:lower')),
(pg_temp.sid('pd:upper_lower:4:4:upper'),pg_temp.sid('p:upper_lower'),4,4,pg_temp.sid('w:upper')),
(pg_temp.sid('pd:upper_lower:4:5:lower'),pg_temp.sid('p:upper_lower'),4,5,pg_temp.sid('w:lower')),
(pg_temp.sid('pd:upper_lower:5:1:upper'),pg_temp.sid('p:upper_lower'),5,1,pg_temp.sid('w:upper')),
(pg_temp.sid('pd:upper_lower:5:2:lower'),pg_temp.sid('p:upper_lower'),5,2,pg_temp.sid('w:lower')),
(pg_temp.sid('pd:upper_lower:5:4:upper'),pg_temp.sid('p:upper_lower'),5,4,pg_temp.sid('w:upper')),
(pg_temp.sid('pd:upper_lower:5:5:lower'),pg_temp.sid('p:upper_lower'),5,5,pg_temp.sid('w:lower')),
(pg_temp.sid('pd:upper_lower:6:1:upper'),pg_temp.sid('p:upper_lower'),6,1,pg_temp.sid('w:upper')),
(pg_temp.sid('pd:upper_lower:6:2:lower'),pg_temp.sid('p:upper_lower'),6,2,pg_temp.sid('w:lower')),
(pg_temp.sid('pd:upper_lower:6:4:upper'),pg_temp.sid('p:upper_lower'),6,4,pg_temp.sid('w:upper')),
(pg_temp.sid('pd:upper_lower:6:5:lower'),pg_temp.sid('p:upper_lower'),6,5,pg_temp.sid('w:lower')),
(pg_temp.sid('pd:upper_lower:7:1:upper'),pg_temp.sid('p:upper_lower'),7,1,pg_temp.sid('w:upper')),
(pg_temp.sid('pd:upper_lower:7:2:lower'),pg_temp.sid('p:upper_lower'),7,2,pg_temp.sid('w:lower')),
(pg_temp.sid('pd:upper_lower:7:4:upper'),pg_temp.sid('p:upper_lower'),7,4,pg_temp.sid('w:upper')),
(pg_temp.sid('pd:upper_lower:7:5:lower'),pg_temp.sid('p:upper_lower'),7,5,pg_temp.sid('w:lower')),
(pg_temp.sid('pd:upper_lower:8:1:upper'),pg_temp.sid('p:upper_lower'),8,1,pg_temp.sid('w:upper')),
(pg_temp.sid('pd:upper_lower:8:2:lower'),pg_temp.sid('p:upper_lower'),8,2,pg_temp.sid('w:lower')),
(pg_temp.sid('pd:upper_lower:8:4:upper'),pg_temp.sid('p:upper_lower'),8,4,pg_temp.sid('w:upper')),
(pg_temp.sid('pd:upper_lower:8:5:lower'),pg_temp.sid('p:upper_lower'),8,5,pg_temp.sid('w:lower')),
(pg_temp.sid('pd:five_by_five:1:1:fxf_a'),pg_temp.sid('p:five_by_five'),1,1,pg_temp.sid('w:fxf_a')),
(pg_temp.sid('pd:five_by_five:1:3:fxf_b'),pg_temp.sid('p:five_by_five'),1,3,pg_temp.sid('w:fxf_b')),
(pg_temp.sid('pd:five_by_five:1:5:fxf_a'),pg_temp.sid('p:five_by_five'),1,5,pg_temp.sid('w:fxf_a')),
(pg_temp.sid('pd:five_by_five:2:1:fxf_b'),pg_temp.sid('p:five_by_five'),2,1,pg_temp.sid('w:fxf_b')),
(pg_temp.sid('pd:five_by_five:2:3:fxf_a'),pg_temp.sid('p:five_by_five'),2,3,pg_temp.sid('w:fxf_a')),
(pg_temp.sid('pd:five_by_five:2:5:fxf_b'),pg_temp.sid('p:five_by_five'),2,5,pg_temp.sid('w:fxf_b')),
(pg_temp.sid('pd:five_by_five:3:1:fxf_a'),pg_temp.sid('p:five_by_five'),3,1,pg_temp.sid('w:fxf_a')),
(pg_temp.sid('pd:five_by_five:3:3:fxf_b'),pg_temp.sid('p:five_by_five'),3,3,pg_temp.sid('w:fxf_b')),
(pg_temp.sid('pd:five_by_five:3:5:fxf_a'),pg_temp.sid('p:five_by_five'),3,5,pg_temp.sid('w:fxf_a')),
(pg_temp.sid('pd:five_by_five:4:1:fxf_b'),pg_temp.sid('p:five_by_five'),4,1,pg_temp.sid('w:fxf_b')),
(pg_temp.sid('pd:five_by_five:4:3:fxf_a'),pg_temp.sid('p:five_by_five'),4,3,pg_temp.sid('w:fxf_a')),
(pg_temp.sid('pd:five_by_five:4:5:fxf_b'),pg_temp.sid('p:five_by_five'),4,5,pg_temp.sid('w:fxf_b')),
(pg_temp.sid('pd:five_by_five:5:1:fxf_a'),pg_temp.sid('p:five_by_five'),5,1,pg_temp.sid('w:fxf_a')),
(pg_temp.sid('pd:five_by_five:5:3:fxf_b'),pg_temp.sid('p:five_by_five'),5,3,pg_temp.sid('w:fxf_b')),
(pg_temp.sid('pd:five_by_five:5:5:fxf_a'),pg_temp.sid('p:five_by_five'),5,5,pg_temp.sid('w:fxf_a')),
(pg_temp.sid('pd:five_by_five:6:1:fxf_b'),pg_temp.sid('p:five_by_five'),6,1,pg_temp.sid('w:fxf_b')),
(pg_temp.sid('pd:five_by_five:6:3:fxf_a'),pg_temp.sid('p:five_by_five'),6,3,pg_temp.sid('w:fxf_a')),
(pg_temp.sid('pd:five_by_five:6:5:fxf_b'),pg_temp.sid('p:five_by_five'),6,5,pg_temp.sid('w:fxf_b')),
(pg_temp.sid('pd:five_by_five:7:1:fxf_a'),pg_temp.sid('p:five_by_five'),7,1,pg_temp.sid('w:fxf_a')),
(pg_temp.sid('pd:five_by_five:7:3:fxf_b'),pg_temp.sid('p:five_by_five'),7,3,pg_temp.sid('w:fxf_b')),
(pg_temp.sid('pd:five_by_five:7:5:fxf_a'),pg_temp.sid('p:five_by_five'),7,5,pg_temp.sid('w:fxf_a')),
(pg_temp.sid('pd:five_by_five:8:1:fxf_b'),pg_temp.sid('p:five_by_five'),8,1,pg_temp.sid('w:fxf_b')),
(pg_temp.sid('pd:five_by_five:8:3:fxf_a'),pg_temp.sid('p:five_by_five'),8,3,pg_temp.sid('w:fxf_a')),
(pg_temp.sid('pd:five_by_five:8:5:fxf_b'),pg_temp.sid('p:five_by_five'),8,5,pg_temp.sid('w:fxf_b')),
(pg_temp.sid('pd:fat_loss:1:1:fb_a'),pg_temp.sid('p:fat_loss'),1,1,pg_temp.sid('w:fb_a')),
(pg_temp.sid('pd:fat_loss:1:2:metcon'),pg_temp.sid('p:fat_loss'),1,2,pg_temp.sid('w:metcon')),
(pg_temp.sid('pd:fat_loss:1:4:amrap20'),pg_temp.sid('p:fat_loss'),1,4,pg_temp.sid('w:amrap20')),
(pg_temp.sid('pd:fat_loss:1:5:intervals'),pg_temp.sid('p:fat_loss'),1,5,pg_temp.sid('w:intervals')),
(pg_temp.sid('pd:fat_loss:1:6:mobility'),pg_temp.sid('p:fat_loss'),1,6,pg_temp.sid('w:mobility')),
(pg_temp.sid('pd:fat_loss:2:1:fb_a'),pg_temp.sid('p:fat_loss'),2,1,pg_temp.sid('w:fb_a')),
(pg_temp.sid('pd:fat_loss:2:2:metcon'),pg_temp.sid('p:fat_loss'),2,2,pg_temp.sid('w:metcon')),
(pg_temp.sid('pd:fat_loss:2:4:amrap20'),pg_temp.sid('p:fat_loss'),2,4,pg_temp.sid('w:amrap20')),
(pg_temp.sid('pd:fat_loss:2:5:intervals'),pg_temp.sid('p:fat_loss'),2,5,pg_temp.sid('w:intervals')),
(pg_temp.sid('pd:fat_loss:2:6:mobility'),pg_temp.sid('p:fat_loss'),2,6,pg_temp.sid('w:mobility')),
(pg_temp.sid('pd:fat_loss:3:1:fb_a'),pg_temp.sid('p:fat_loss'),3,1,pg_temp.sid('w:fb_a')),
(pg_temp.sid('pd:fat_loss:3:2:metcon'),pg_temp.sid('p:fat_loss'),3,2,pg_temp.sid('w:metcon')),
(pg_temp.sid('pd:fat_loss:3:4:amrap20'),pg_temp.sid('p:fat_loss'),3,4,pg_temp.sid('w:amrap20')),
(pg_temp.sid('pd:fat_loss:3:5:intervals'),pg_temp.sid('p:fat_loss'),3,5,pg_temp.sid('w:intervals')),
(pg_temp.sid('pd:fat_loss:3:6:mobility'),pg_temp.sid('p:fat_loss'),3,6,pg_temp.sid('w:mobility')),
(pg_temp.sid('pd:fat_loss:4:1:fb_a'),pg_temp.sid('p:fat_loss'),4,1,pg_temp.sid('w:fb_a')),
(pg_temp.sid('pd:fat_loss:4:2:metcon'),pg_temp.sid('p:fat_loss'),4,2,pg_temp.sid('w:metcon')),
(pg_temp.sid('pd:fat_loss:4:4:amrap20'),pg_temp.sid('p:fat_loss'),4,4,pg_temp.sid('w:amrap20')),
(pg_temp.sid('pd:fat_loss:4:5:intervals'),pg_temp.sid('p:fat_loss'),4,5,pg_temp.sid('w:intervals')),
(pg_temp.sid('pd:fat_loss:4:6:mobility'),pg_temp.sid('p:fat_loss'),4,6,pg_temp.sid('w:mobility')),
(pg_temp.sid('pd:home:1:1:home'),pg_temp.sid('p:home'),1,1,pg_temp.sid('w:home')),
(pg_temp.sid('pd:home:1:3:home'),pg_temp.sid('p:home'),1,3,pg_temp.sid('w:home')),
(pg_temp.sid('pd:home:1:5:home'),pg_temp.sid('p:home'),1,5,pg_temp.sid('w:home')),
(pg_temp.sid('pd:home:1:7:mobility'),pg_temp.sid('p:home'),1,7,pg_temp.sid('w:mobility')),
(pg_temp.sid('pd:home:2:1:home'),pg_temp.sid('p:home'),2,1,pg_temp.sid('w:home')),
(pg_temp.sid('pd:home:2:3:home'),pg_temp.sid('p:home'),2,3,pg_temp.sid('w:home')),
(pg_temp.sid('pd:home:2:5:home'),pg_temp.sid('p:home'),2,5,pg_temp.sid('w:home')),
(pg_temp.sid('pd:home:2:7:mobility'),pg_temp.sid('p:home'),2,7,pg_temp.sid('w:mobility')),
(pg_temp.sid('pd:home:3:1:home'),pg_temp.sid('p:home'),3,1,pg_temp.sid('w:home')),
(pg_temp.sid('pd:home:3:3:home'),pg_temp.sid('p:home'),3,3,pg_temp.sid('w:home')),
(pg_temp.sid('pd:home:3:5:home'),pg_temp.sid('p:home'),3,5,pg_temp.sid('w:home')),
(pg_temp.sid('pd:home:3:7:mobility'),pg_temp.sid('p:home'),3,7,pg_temp.sid('w:mobility')),
(pg_temp.sid('pd:home:4:1:home'),pg_temp.sid('p:home'),4,1,pg_temp.sid('w:home')),
(pg_temp.sid('pd:home:4:3:home'),pg_temp.sid('p:home'),4,3,pg_temp.sid('w:home')),
(pg_temp.sid('pd:home:4:5:home'),pg_temp.sid('p:home'),4,5,pg_temp.sid('w:home')),
(pg_temp.sid('pd:home:4:7:mobility'),pg_temp.sid('p:home'),4,7,pg_temp.sid('w:mobility'))
on conflict (id) do nothing;
