-- PTPN everyday meal ideas. Safe to re-run (deterministic ids, on conflict do nothing).
create or replace function pg_temp.sid(t text) returns uuid language sql immutable as $$ select extensions.uuid_generate_v5('6f1c1e4a-8d3b-4c55-9a9e-5b1d2e7c0a11'::uuid, t) $$;

insert into public.foods (id, name, serving_label, serving_g, kcal, protein, carbs, fat) values
(pg_temp.sid('food:Mixed nuts'),'Mixed nuts','1 handful (30 g)',30,607,20,21,54),
(pg_temp.sid('food:Popcorn, air-popped'),'Popcorn, air-popped','1 bowl (25 g)',25,387,12,78,4.5),
(pg_temp.sid('food:Wholemeal crackers'),'Wholemeal crackers','4 crackers (25 g)',25,413,11,64,12),
(pg_temp.sid('food:Baked beans'),'Baked beans','1/2 can (200 g)',200,90,4.7,15.5,0.4),
(pg_temp.sid('food:Potato, baked'),'Potato, baked','1 medium (220 g)',220,93,2.5,21,0.1),
(pg_temp.sid('food:Olives'),'Olives','10 olives (40 g)',40,115,0.8,6,11)
on conflict (id) do nothing;

insert into public.recipes (id, name, meal_type, description, prep_min, kcal, protein, carbs, fat, ingredients, steps, tags, image_url) values
(pg_temp.sid('recipe:Banana and peanut butter porridge'),'Banana and peanut butter porridge','breakfast','Creamy oats cooked in milk with sliced banana and a spoon of peanut butter.',8,541,23.5,81.4,16.2,array['60 g oats, dry','250 ml milk, semi-skimmed','100 g banana','15 g peanut butter','5 g honey','1/4 tsp ground cinnamon']::text[],array['Heat the oats and milk in a pan, stirring, for 4 to 5 minutes until thick.','Pour into a bowl and top with sliced banana.','Swirl in the peanut butter and honey and finish with cinnamon.']::text[],array['quick','high fibre']::text[],'https://images.pexels.com/photos/9226325/pexels-photo-9226325.jpeg?auto=compress&cs=tinysrgb&w=800'),
(pg_temp.sid('recipe:Poached eggs on toast with spinach'),'Poached eggs on toast with spinach','breakfast','Three soft eggs on wholemeal toast over wilted spinach.',10,437,29.8,31.9,20.9,array['150 g eggs, whole','70 g wholemeal bread','60 g spinach','5 g butter','1 tsp white vinegar','black pepper to taste']::text[],array['Wilt the spinach in a dry pan for a minute and set aside.','Poach the eggs in barely simmering water with a splash of vinegar for 3 minutes.','Toast and lightly butter the bread, top with spinach and the eggs.']::text[],array['high protein','quick']::text[],'https://images.pexels.com/photos/10785005/pexels-photo-10785005.jpeg?auto=compress&cs=tinysrgb&w=800'),
(pg_temp.sid('recipe:Avocado and egg toast'),'Avocado and egg toast','breakfast','Mashed avocado and tomato on wholemeal toast with a fried or boiled egg.',10,439,23.6,37.7,22.3,array['70 g wholemeal bread','70 g avocado','100 g eggs, whole','60 g tomato','1 tsp lemon juice','pinch of chilli flakes']::text[],array['Toast the bread and mash the avocado with lemon juice and a pinch of salt.','Cook the eggs the way you like them.','Spread the avocado on the toast and top with tomato, the eggs and chilli flakes.']::text[],array['vegetarian','quick']::text[],'https://images.pexels.com/photos/6327123/pexels-photo-6327123.jpeg?auto=compress&cs=tinysrgb&w=800'),
(pg_temp.sid('recipe:Banana and spinach protein smoothie'),'Banana and spinach protein smoothie','breakfast','A thick green smoothie with whey and oats that keeps you full.',5,468,40.1,62.8,8.6,array['120 g banana','40 g spinach','250 ml milk, semi-skimmed','30 g whey protein powder','30 g oats, dry','4 ice cubes']::text[],array['Add the milk, banana, spinach, whey and oats to a blender.','Blend with a handful of ice until completely smooth.','Drink straight away.']::text[],array['high protein','no cook']::text[],'https://images.pexels.com/photos/28909422/pexels-photo-28909422.jpeg?auto=compress&cs=tinysrgb&w=800'),
(pg_temp.sid('recipe:Egg breakfast burrito'),'Egg breakfast burrito','breakfast','Scrambled eggs, black beans and cheese rolled in a warm tortilla.',12,562,33.7,50.5,24.5,array['62 g tortilla wrap','150 g eggs, whole','60 g black beans, cooked','40 g salsa','15 g cheddar cheese','1/2 tsp smoked paprika']::text[],array['Warm the beans with a pinch of paprika.','Scramble the eggs in a non-stick pan until just set.','Fill the tortilla with eggs, beans, cheese and salsa, fold in the ends and roll.']::text[],array['high protein','mexican']::text[],'https://images.pexels.com/photos/27365284/pexels-photo-27365284.jpeg?auto=compress&cs=tinysrgb&w=800'),
(pg_temp.sid('recipe:Veggie egg muffins'),'Veggie egg muffins','breakfast','Baked egg cups packed with pepper and spinach, served with toast.',30,501,37.8,21.1,28.8,array['200 g eggs, whole','60 g bell pepper','40 g spinach','25 g cheddar cheese','35 g wholemeal bread','black pepper to taste']::text[],array['Heat the oven to 180C and grease a muffin tin.','Whisk the eggs, then stir in chopped pepper, spinach and cheese and pour into the tin.','Bake for 18 to 20 minutes and serve with toast. They keep for three days in the fridge.']::text[],array['meal prep','high protein']::text[],'https://images.pexels.com/photos/14302150/pexels-photo-14302150.jpeg?auto=compress&cs=tinysrgb&w=800'),
(pg_temp.sid('recipe:Berry chia pudding'),'Berry chia pudding','breakfast','Make it the night before: chia soaked in milk and yogurt, topped with berries.',5,425,24.9,46.0,18.3,array['30 g chia seeds','200 ml milk, semi-skimmed','100 g Greek yogurt 0% fat','80 g blueberries','8 g honey','10 g almonds','1/2 tsp vanilla extract']::text[],array['Stir the chia, milk, yogurt, honey and vanilla together in a jar.','Leave in the fridge overnight, stirring once after 10 minutes.','Top with blueberries and chopped almonds.']::text[],array['meal prep','no cook']::text[],'https://images.pexels.com/photos/5589029/pexels-photo-5589029.jpeg?auto=compress&cs=tinysrgb&w=800'),
(pg_temp.sid('recipe:Chicken, rice and broccoli meal prep box'),'Chicken, rice and broccoli meal prep box','lunch','The classic lunch box: plain, filling and easy to batch for the week.',25,528,53.9,49.9,11.3,array['150 g chicken breast, cooked','150 g white rice, cooked','120 g broccoli','5 g olive oil','1/2 lemon','1/2 tsp garlic powder','black pepper to taste']::text[],array['Season the chicken with garlic powder and pepper and bake or grill until cooked through.','Steam the broccoli for 4 minutes.','Pack with the rice, drizzle the oil and squeeze over lemon.']::text[],array['meal prep','high protein']::text[],'https://images.pexels.com/photos/24738520/pexels-photo-24738520.jpeg?auto=compress&cs=tinysrgb&w=800'),
(pg_temp.sid('recipe:Chicken salad sandwich'),'Chicken salad sandwich','lunch','Shredded chicken in a light yogurt and mustard dressing on wholemeal bread.',10,465,46.0,54.9,7.0,array['80 g wholemeal bread','100 g chicken breast, cooked','30 g Greek yogurt 0% fat','30 g mixed salad leaves','50 g tomato','5 g Dijon mustard','130 g apple','black pepper to taste']::text[],array['Mix the shredded chicken with the yogurt, mustard and pepper.','Layer onto the bread with leaves and sliced tomato.','Serve with the apple.']::text[],array['quick','high protein']::text[],'https://images.pexels.com/photos/12469931/pexels-photo-12469931.jpeg?auto=compress&cs=tinysrgb&w=800'),
(pg_temp.sid('recipe:Cheesy bean jacket potato'),'Cheesy bean jacket potato','lunch','A baked potato topped with warm baked beans and a little melted cheese.',55,494,21.4,77.3,10.8,array['250 g potato, baked','150 g baked beans','30 g cheddar cheese','40 g mixed salad leaves','black pepper to taste']::text[],array['Prick the potato and bake at 200C for about 50 minutes (or microwave for 8 to 10 minutes).','Warm the beans.','Split the potato, pile on the beans and cheese and serve with the leaves.']::text[],array['vegetarian','budget']::text[],'https://images.pexels.com/photos/4110470/pexels-photo-4110470.jpeg?auto=compress&cs=tinysrgb&w=800'),
(pg_temp.sid('recipe:Greek salad with grilled chicken'),'Greek salad with grilled chicken','lunch','Crisp cucumber, tomato, feta and olives with sliced chicken and a little bread.',15,569,53.3,29.9,26.1,array['130 g chicken breast, cooked','100 g cucumber','120 g tomato','40 g feta','30 g olives','20 g onion','8 g olive oil','40 g wholemeal bread','1/2 tsp dried oregano','1 tbsp lemon juice']::text[],array['Chop the cucumber, tomato and onion into chunks and add the olives.','Toss with olive oil, lemon juice and oregano and crumble over the feta.','Top with sliced chicken and serve with the bread.']::text[],array['high protein','mediterranean']::text[],'https://images.pexels.com/photos/31233885/pexels-photo-31233885.jpeg?auto=compress&cs=tinysrgb&w=800'),
(pg_temp.sid('recipe:Egg and avocado wrap'),'Egg and avocado wrap','lunch','Chopped boiled eggs, avocado and spinach in a tortilla.',10,539,29.7,42.6,28.4,array['62 g tortilla wrap','150 g eggs, whole','60 g avocado','30 g spinach','60 g tomato','30 g Greek yogurt 0% fat','1 tsp lemon juice','black pepper to taste']::text[],array['Boil the eggs for 8 minutes, cool and chop.','Mash the avocado with the yogurt and lemon juice and mix in the eggs.','Spoon onto the wrap with spinach and tomato and roll up.']::text[],array['vegetarian','quick']::text[],'https://images.pexels.com/photos/37550322/pexels-photo-37550322.jpeg?auto=compress&cs=tinysrgb&w=800'),
(pg_temp.sid('recipe:Minestrone soup with wholemeal bread'),'Minestrone soup with wholemeal bread','lunch','A thick vegetable, bean and pasta soup with a slice of bread.',30,567,28.1,90.9,11.1,array['100 g kidney beans, cooked','200 g chopped tomatoes, canned','60 g carrot','80 g courgette','80 g pasta, cooked','40 g onion','50 g green beans','8 g parmesan','50 g wholemeal bread','5 g olive oil','400 ml vegetable stock','1 clove garlic','1 tsp dried basil']::text[],array['Soften the onion, carrot and garlic in the oil for 5 minutes.','Add the tomatoes, stock, courgette, green beans and kidney beans and simmer for 15 minutes.','Stir in the cooked pasta, serve with parmesan and the bread.']::text[],array['vegetarian','one pot']::text[],'https://images.pexels.com/photos/31321820/pexels-photo-31321820.jpeg?auto=compress&cs=tinysrgb&w=800'),
(pg_temp.sid('recipe:Tuna and sweetcorn pasta'),'Tuna and sweetcorn pasta','lunch','A quick yogurt-dressed pasta with tuna, sweetcorn and tomatoes.',15,604,52.0,79.3,9.3,array['200 g pasta, cooked','120 g tuna, canned in water, drained','60 g sweetcorn','60 g Greek yogurt 0% fat','80 g tomato','5 g olive oil','20 g mixed salad leaves','1 tbsp lemon juice','black pepper to taste']::text[],array['Cook the pasta, drain and let it cool a little.','Mix the yogurt with lemon juice, oil and pepper.','Toss through the pasta with the tuna, sweetcorn and chopped tomato and serve on the leaves.']::text[],array['quick','high protein']::text[],'https://images.pexels.com/photos/31637791/pexels-photo-31637791.jpeg?auto=compress&cs=tinysrgb&w=800'),
(pg_temp.sid('recipe:Baked chicken with sweet potato and green beans'),'Baked chicken with sweet potato and green beans','dinner','Simple oven-baked chicken breast with roasted sweet potato wedges.',40,567,62.0,49.8,13.1,array['180 g chicken breast, cooked','200 g sweet potato, baked','120 g green beans','6 g olive oil','1/2 tsp paprika','1/2 tsp garlic powder','black pepper to taste']::text[],array['Heat the oven to 200C. Toss the sweet potato wedges in half the oil and roast for 15 minutes.','Rub the chicken with the rest of the oil and the spices, add to the tray and roast for 20 to 25 minutes.','Steam the green beans and serve everything together.']::text[],array['high protein','one pan']::text[],'https://images.pexels.com/photos/28292007/pexels-photo-28292007.jpeg?auto=compress&cs=tinysrgb&w=800'),
(pg_temp.sid('recipe:Chicken fajitas'),'Chicken fajitas','dinner','Sizzling chicken, peppers and onion in warm tortillas with salsa and yogurt.',25,736,60.7,67.5,24.1,array['140 g chicken breast, cooked','120 g bell pepper','60 g onion','93 g tortilla wrap','40 g salsa','40 g Greek yogurt 0% fat','10 g cheddar cheese','25 g avocado','4 g olive oil','2 tsp fajita seasoning','1/2 lime']::text[],array['Slice the chicken, peppers and onion into strips and toss with the oil and seasoning.','Fry in a hot pan for 6 to 8 minutes until charred.','Fill the warm tortillas and top with salsa, yogurt, cheese and avocado.']::text[],array['high protein','mexican']::text[],'https://images.pexels.com/photos/32371267/pexels-photo-32371267.jpeg?auto=compress&cs=tinysrgb&w=800'),
(pg_temp.sid('recipe:Lean shepherd''s pie'),'Lean shepherd''s pie','dinner','Lean beef and vegetable filling under a light mash topping.',50,641,52.8,74.1,15.2,array['150 g beef mince 5% fat, cooked','250 g potato, boiled','60 g carrot','60 g peas, frozen','50 g onion','100 g chopped tomatoes, canned','30 ml milk, semi-skimmed','10 g cheddar cheese','1 tbsp worcestershire sauce','150 ml beef stock','1/2 tsp dried thyme']::text[],array['Brown the mince with the onion and carrot, then add the tomatoes, stock, worcestershire and thyme and simmer for 15 minutes with the peas.','Mash the potato with the milk and pepper.','Spoon the mince into a dish, cover with the mash and cheese and bake at 200C for 20 minutes.']::text[],array['comfort','meal prep']::text[],'https://images.pexels.com/photos/36040894/pexels-photo-36040894.jpeg?auto=compress&cs=tinysrgb&w=800'),
(pg_temp.sid('recipe:Grilled salmon with new potatoes and asparagus'),'Grilled salmon with new potatoes and asparagus','dinner','A fillet of salmon with buttery potatoes and charred asparagus.',25,551,39.4,44.7,23.3,array['150 g salmon fillet, cooked','200 g potato, boiled','120 g asparagus','5 g olive oil','1/2 lemon','1 tbsp fresh dill','black pepper to taste']::text[],array['Boil the potatoes for 15 minutes.','Grill or pan-fry the salmon for 4 minutes each side and griddle the asparagus with the oil.','Serve with lemon and dill.']::text[],array['omega-3','high protein']::text[],'https://images.pexels.com/photos/5152283/pexels-photo-5152283.jpeg?auto=compress&cs=tinysrgb&w=800'),
(pg_temp.sid('recipe:Stuffed peppers with beef and rice'),'Stuffed peppers with beef and rice','dinner','Roasted peppers filled with seasoned mince, rice and melted mozzarella.',45,558,47.0,56.8,14.8,array['250 g bell pepper','120 g beef mince 5% fat, cooked','120 g white rice, cooked','100 g chopped tomatoes, canned','40 g onion','30 g mozzarella','1 tsp smoked paprika','1 clove garlic']::text[],array['Halve the peppers and remove the seeds.','Mix the mince, rice, tomatoes, onion, garlic and paprika and spoon into the pepper halves.','Top with mozzarella and bake at 200C for 30 minutes.']::text[],array['high protein','meal prep']::text[],'https://images.pexels.com/photos/35718863/pexels-photo-35718863.jpeg?auto=compress&cs=tinysrgb&w=800'),
(pg_temp.sid('recipe:Vegetable and bean chilli with rice'),'Vegetable and bean chilli with rice','dinner','A big pot of two-bean chilli with pepper and courgette.',35,634,33.1,104.2,10.2,array['100 g kidney beans, cooked','80 g black beans, cooked','200 g chopped tomatoes, canned','100 g bell pepper','50 g onion','80 g courgette','160 g brown rice, cooked','20 g cheddar cheese','30 g Greek yogurt 0% fat','1 tsp chilli powder','1 tsp ground cumin','1 clove garlic']::text[],array['Soften the onion, pepper and courgette with garlic, chilli and cumin.','Add the tomatoes and beans and simmer for 20 minutes.','Serve over rice with grated cheese and a spoon of yogurt.']::text[],array['vegetarian','meal prep']::text[],'https://images.pexels.com/photos/32667184/pexels-photo-32667184.jpeg?auto=compress&cs=tinysrgb&w=800'),
(pg_temp.sid('recipe:Grilled pork loin with roast potatoes and broccoli'),'Grilled pork loin with roast potatoes and broccoli','dinner','Lean pork with crisp roast potatoes and steamed broccoli.',40,546,51.7,51.9,14.7,array['170 g pork tenderloin, cooked','220 g potato, boiled','120 g broccoli','8 g olive oil','1 sprig rosemary','1 clove garlic','black pepper to taste']::text[],array['Roast the halved potatoes with half the oil and rosemary at 210C for 35 minutes.','Rub the pork with the remaining oil, garlic and pepper and grill or roast for 20 minutes, then rest and slice.','Steam the broccoli and serve together.']::text[],array['high protein','weekend']::text[],'https://images.pexels.com/photos/32974951/pexels-photo-32974951.jpeg?auto=compress&cs=tinysrgb&w=800'),
(pg_temp.sid('recipe:Banana'),'Banana','snack','The easiest grab-and-go snack.',1,107,1.3,27.4,0.4,array['120 g banana']::text[],array['Peel and eat. Pair with a handful of nuts if you need more staying power.']::text[],array['no cook','quick']::text[],'https://images.pexels.com/photos/4399936/pexels-photo-4399936.jpeg?auto=compress&cs=tinysrgb&w=800'),
(pg_temp.sid('recipe:Handful of mixed nuts'),'Handful of mixed nuts','snack','A palm-sized portion of almonds, walnuts, cashews and peanuts.',1,182,6.0,6.3,16.2,array['30 g mixed nuts']::text[],array['Measure out 30 g so it stays a snack and not a meal.']::text[],array['no cook','healthy fats']::text[],'https://images.pexels.com/photos/9615877/pexels-photo-9615877.jpeg?auto=compress&cs=tinysrgb&w=800'),
(pg_temp.sid('recipe:Cheese and wholemeal crackers'),'Cheese and wholemeal crackers','snack','A small cheddar slice stack on wholemeal crackers with a few grapes.',3,266,10.7,27.2,13.0,array['30 g cheddar cheese','25 g wholemeal crackers','60 g grapes']::text[],array['Slice the cheese and lay it on the crackers.','Serve with the grapes.']::text[],array['quick','no cook']::text[],'https://images.pexels.com/photos/39831697/pexels-photo-39831697.jpeg?auto=compress&cs=tinysrgb&w=800'),
(pg_temp.sid('recipe:Protein bar'),'Protein bar','snack','A ready-made bar for when you are out and about.',1,210,19.8,21.0,6.0,array['60 g protein bar']::text[],array['Check the label: aim for around 20 g protein and under 4 g sugar.']::text[],array['no cook','high protein']::text[],'https://images.pexels.com/photos/17763560/pexels-photo-17763560.jpeg?auto=compress&cs=tinysrgb&w=800'),
(pg_temp.sid('recipe:Air-popped popcorn'),'Air-popped popcorn','snack','A big bowl of plain popcorn for very few calories.',5,97,3.0,19.5,1.1,array['25 g popcorn, air-popped','pinch of salt']::text[],array['Pop the kernels in an air popper or a covered pan with no oil.','Season with a pinch of salt.']::text[],array['low calorie','high fibre']::text[],'https://images.pexels.com/photos/28182512/pexels-photo-28182512.jpeg?auto=compress&cs=tinysrgb&w=800'),
(pg_temp.sid('recipe:Clementines'),'Clementines','snack','Two easy-peel citrus fruits with a good dose of vitamin C.',2,75,1.4,18.9,0.2,array['160 g orange']::text[],array['Peel and eat.']::text[],array['no cook','low calorie']::text[],'https://images.pexels.com/photos/7669180/pexels-photo-7669180.jpeg?auto=compress&cs=tinysrgb&w=800'),
(pg_temp.sid('recipe:Turkey and cucumber roll-ups'),'Turkey and cucumber roll-ups','snack','Sliced turkey rolled around cucumber and a little cream cheese.',5,120,20.2,3.4,2.7,array['60 g turkey breast, cooked','60 g cucumber','20 g light cream cheese','black pepper to taste']::text[],array['Spread the cream cheese on the turkey slices.','Lay a cucumber stick on each and roll up.']::text[],array['high protein','low calorie']::text[],'https://images.pexels.com/photos/35372727/pexels-photo-35372727.jpeg?auto=compress&cs=tinysrgb&w=800')
on conflict (id) do nothing;
