"""Exercises from the MyGym London exercise list (compiled from 37 client workout sheets) that were not already in the
library. Names that already existed (Rowing machine, Medicine ball slam, Assault bike, Jump rope, Back squat, Push-up,
Lat pulldown and so on) are not repeated. Variations are folded into the cues."""

# name, muscle, equipment, category, cue
NEW_EX = [
 # cardio / conditioning
 ("Sled push n pull", "Full body", "Sled", "cardio", "Push the sled down the lane, turn and pull it back on the rope. Count laps. Also written push n push or pull n pull."),
 ("TRX push n pull", "Full body", "TRX", "cardio", "Alternate a TRX press-up with a TRX row, keeping the body in one straight line."),
 ("Rope waves", "Full body", "Ropes", "cardio", "Hinge slightly and whip the ropes in fast, even waves, alternating or both arms together."),
 ("Ball slam combo", "Full body", "Medicine ball", "cardio", "Slam the ball, then flow into a run, squat or lunge before the next rep."),
 ("Jumping jacks", "Full body", "Bodyweight", "cardio", "Jump the feet wide as the arms go overhead, then back together. Land softly."),
 ("Boxing", "Full body", "Gloves or bag", "cardio", "Work in rounds or combinations: jab, cross, hook, with a tight guard and rotating hips."),
 ("Walking", "Cardio", "None", "cardio", "Brisk walk outdoors or on the treadmill, timed or as HIT intervals."),
 ("Cross trainer", "Cardio", "Cross trainer", "cardio", "Stand tall, drive through the whole foot and push and pull the handles in rhythm."),
 ("Stepper drills", "Legs", "Box", "cardio", "Fast step patterns on a box: side to side, high knee or alternating."),
 ("High knees", "Legs", "Bodyweight", "cardio", "Run on the spot driving the knees to hip height with quick ground contacts. Ladder and kneeled versions also used."),
 ("Ladder drills", "Legs", "Agility ladder", "cardio", "Quick feet through the ladder, one foot per square, light on the toes."),
 ("Side shuffles", "Legs", "Bodyweight", "cardio", "Stay low in a half squat and shuffle sideways without crossing the feet."),
 ("Punches", "Shoulders", "Dumbbells or landmine", "cardio", "Drive the weight forward in a straight line from a staggered stance, rotating through the hips."),
 ("Power bag pull", "Full body", "Power bag", "cardio", "Pull or drag the bag with a flat back and powerful hip drive."),
 # lower body
 ("Bodyweight squat", "Quads", "Bodyweight", "strength", "Feet shoulder width, sit between the hips and stand tall with the chest up."),
 ("TRX squat", "Quads", "TRX", "strength", "Hold the handles for balance, sit back and down, drive up through the heels."),
 ("Smith squat", "Quads", "Smith machine", "strength", "Bar on the upper back, feet slightly forward, squat to parallel or lower. Pulse and off-bench versions are used."),
 ("Dumbbell squat", "Quads", "Dumbbells", "strength", "Hold dumbbells at your sides or shoulders and squat to depth, optionally to a bench."),
 ("Squat n press", "Full body", "Dumbbells", "strength", "Squat, then drive up and press the weight overhead in one flow. Works with dumbbells, barbell, kettlebell or landmine."),
 ("Kettlebell band squat", "Quads", "Kettlebell and band", "strength", "Band around the knees, kettlebell at the chest. Squat while pushing the knees out against the band."),
 ("Kettlebell front squat", "Quads", "Kettlebell", "strength", "Rack the kettlebell at the chest and squat upright with the elbows tucked."),
 ("Side lunge", "Quads", "Bodyweight or vest", "strength", "Step wide to one side, sit back into that hip, keep the other leg straight, push back to centre."),
 ("Dumbbell side lunge", "Quads", "Dumbbells", "strength", "Hold a dumbbell at the chest and lunge sideways, sitting back into the working hip."),
 ("Side lunge with side raise", "Quads", "Dumbbells", "strength", "Lunge to the side and raise the dumbbells out to shoulder height as you stand."),
 ("TRX side lunge", "Quads", "TRX", "strength", "Hold the TRX for balance, step to the side and sit into the lunge, then push back."),
 ("Lunge", "Quads", "Dumbbells", "strength", "Step forward or back with both knees near 90 degrees. Dumbbells, barbell or bodyweight."),
 ("Lunge n curl", "Quads", "Dumbbells", "strength", "Lunge (walking or stationary) and curl the dumbbells as you stand."),
 ("Lunge n press", "Full body", "Dumbbells", "strength", "Lunge forward or to the side, then press the weights overhead as you stand."),
 ("Back lunge with high knee", "Quads", "Bodyweight", "strength", "Step back into a lunge, then drive the back knee up to hip height as you stand."),
 ("Smith lunge", "Quads", "Smith machine", "strength", "Split stance under the bar, lower the back knee toward the floor, drive through the front heel."),
 ("Kettlebell deadlift", "Hamstrings", "Kettlebell", "strength", "Hinge at the hips with a flat back and lift the kettlebell by standing tall. Stiff-leg version for more hamstring."),
 ("Smith deadlift", "Hamstrings", "Smith machine", "strength", "Hinge and lift the bar along its fixed path with a flat back, hips and chest rising together."),
 ("Shoulder bridge", "Glutes", "Bodyweight", "strength", "Lie on your back with the feet flat, drive the hips up and squeeze the glutes at the top."),
 ("Wall sit", "Quads", "Bodyweight", "strength", "Back flat on the wall, thighs parallel to the floor. Hold for time."),
 ("Inner thigh machine", "Adductors", "Machine", "strength", "Sit tall and squeeze the legs together against the pads, control the return. Cable pull down and lying versions are used too."),
 ("Donkey kick", "Glutes", "Bodyweight", "strength", "On hands and knees, drive one heel to the ceiling keeping the hips square."),
 ("Squat hold", "Quads", "Bodyweight", "strength", "Hold the bottom of a squat with an upright chest. Use a barbell or Smith bar for extra load."),
 ("Squat pulse", "Quads", "Bodyweight", "strength", "Stay in the bottom half of the squat and pulse up and down in small controlled reps."),
 ("Bosu squat", "Quads", "Bosu", "strength", "Stand on the Bosu, squat slowly and keep the knees tracking over the toes."),
 ("Sumo squat", "Quads", "Dumbbells", "strength", "Wide stance, toes out, dumbbell between the legs. Squat deep and squeeze the inner thighs on the way up."),
 ("TRX squat n row", "Full body", "TRX", "strength", "Squat low, then stand and row the handles to the ribs. Pistol squat as a progression."),
 ("Hip raise", "Glutes", "Bodyweight", "strength", "Drive the hips up from the floor or a bench. Single leg for more load."),
 ("Fire hydrant", "Glutes", "Bodyweight", "strength", "On hands and knees, lift one knee out to the side without rotating the hips."),
 ("Back kick", "Glutes", "Bodyweight", "strength", "On hands and knees, kick one leg back and squeeze the glute at the top."),
 ("NLP", "Legs", "Machine", "strength", "Abbreviation as written on the MyGym sheets, not explained there. Edit the cues to match how you run it."),
 ("OLP", "Legs", "Machine", "strength", "Abbreviation as written on the MyGym sheets, not explained there. Edit the cues to match how you run it."),
 # chest and pushing
 ("Smith press", "Chest", "Smith machine", "strength", "Flat bench under the bar, lower to mid chest and press up along the fixed path."),
 ("Incline Smith press", "Chest", "Smith machine", "strength", "Bench at 30 degrees, lower to the upper chest and press up."),
 ("Inverted grip press", "Chest", "Smith machine or dumbbells", "strength", "Palms facing you for a closer chest bias. Decline and narrow versions are used too."),
 ("Dumbbell close grip press", "Chest", "Dumbbells", "strength", "Dumbbells together, elbows in, press up squeezing the chest and triceps. Flat or incline."),
 ("Cable press", "Chest", "Cable", "strength", "Stand in a split stance and press the handles forward from chest height."),
 ("Cable fly", "Chest", "Cable", "strength", "Slight elbow bend, sweep the handles together in an arc. High, mid or low pulley."),
 ("Triceps kickback", "Triceps", "Dumbbells", "strength", "Hinge forward with the upper arm fixed, extend the elbow and squeeze."),
 ("Dumbbell floor press", "Chest", "Dumbbells", "strength", "Lie on the floor and press, letting the triceps touch the floor each rep."),
 ("Plate press", "Chest", "Weight plate", "strength", "Hold a plate at the chest and press it straight out, squeezing the plate."),
 ("Bridge press", "Chest", "Dumbbells", "strength", "Hold a glute bridge while pressing the dumbbells."),
 ("TRX press-up", "Chest", "TRX", "strength", "Hands in the handles, lower the chest between them, keeping a straight body."),
 ("Renegade row", "Back", "Dumbbells", "strength", "Plank on dumbbells and row one side at a time, bracing hard so the hips do not twist."),
 # back and pulling
 ("TRX row", "Back", "TRX", "strength", "Lean back with a straight body and pull the chest to the handles."),
 ("Landmine row", "Back", "Barbell", "strength", "Hinge over the end of the bar and row the handle to the ribs."),
 ("Rope overhead pull down", "Back", "Cable", "strength", "Pull the rope down from overhead to the chest with the elbows driving to the hips. Straight bar also works."),
 ("Cable back fly", "Shoulders", "Cable", "strength", "Pull the handles apart with straight-ish arms to hit the rear delts and upper back."),
 ("Seated back fly", "Shoulders", "Machine", "strength", "Chest on the pad, open the arms wide and squeeze the shoulder blades."),
 ("TRX back fly", "Shoulders", "TRX", "strength", "Lean back and open the arms wide, squeezing the shoulder blades."),
 ("Back extension", "Back", "Bench", "strength", "Hinge at the hips on a back extension bench and lift to a straight line without arching. Hold a dumbbell to progress."),
 ("Pullover", "Back", "Dumbbell or rope", "strength", "Arms long, take the weight overhead and back, then pull it over the chest."),
 ("Superman", "Back", "Bodyweight", "strength", "Lie face down and lift arms and legs together, holding briefly at the top."),
 ("Swimmers", "Back", "Bodyweight", "strength", "Face down, alternate lifting opposite arm and leg in a flutter."),
 ("Press n row", "Full body", "Dumbbells", "strength", "Press then row in one set, keeping the core braced."),
 ("Crawl and pull", "Full body", "Bodyweight", "strength", "Crawl forward low to the ground, then pull yourself or a weight toward you."),
 ("Rope pull", "Back", "Rope", "strength", "Hand over hand rope pulls, leaning back with a tight core."),
 # shoulders and arms
 ("Upright row", "Shoulders", "Barbell", "strength", "Pull the bar to the lower chest with the elbows above the wrists."),
 ("Front raise", "Shoulders", "Dumbbells", "strength", "Raise the weight to shoulder height in front and lower slowly. Plate or cable also work."),
 ("Rotator cuff", "Shoulders", "Band or cable", "mobility", "Elbow tucked at the side, rotate the forearm out and in with light load."),
 ("Shrug", "Traps", "Dumbbells", "strength", "Lift the shoulders straight up toward the ears, pause, lower slowly. Kettlebells work too."),
 ("Incline dumbbell curl", "Biceps", "Dumbbells", "strength", "Bench at 60 degrees, arms hanging back, curl without swinging."),
 ("Rope curl", "Biceps", "Cable", "strength", "Low pulley with a rope, curl and turn the palms up at the top."),
 ("Cable forearm curl", "Forearms", "Cable", "strength", "Forearms resting on the thighs, curl the wrists up and down slowly."),
 ("TRX curl", "Biceps", "TRX", "strength", "Lean back holding the handles and curl the hands toward the forehead."),
 ("Inverted curl", "Biceps", "Bar", "strength", "Overhand grip curl to hit the forearms and brachialis."),
 ("Curl n press", "Shoulders", "Dumbbells", "strength", "Curl the dumbbells, then press them overhead. Seated or standing."),
 ("Clean n press", "Full body", "Barbell, dumbbells or kettlebell", "strength", "Clean the weight to the shoulders, then press overhead in one smooth movement."),
 # core
 ("Ball to leg", "Core", "Medicine ball", "core", "Lie on your back and pass the ball between hands and feet as you crunch up. Also written ball to foot or knees."),
 ("Ball n leg drops", "Core", "Medicine ball", "core", "Hold the ball overhead and lower the legs alternately without arching the back."),
 ("Leg drop", "Core", "Bodyweight", "core", "Lying on your back, lower straight legs toward the floor and lift back up. Single, double or alternating."),
 ("Ball over knee crunch", "Core", "Medicine ball", "core", "Place the ball on the knees and crunch up over it."),
 ("Ball to ball", "Core", "Medicine ball", "core", "Pass between two balls, or hands and feet, while crunching."),
 ("Ball sit-up", "Core", "Medicine ball", "core", "Sit up holding the ball and extend it overhead at the bottom."),
 ("Weighted sit-up", "Core", "Weight plate or ball", "core", "Sit up fully holding the weight. Add a clap, pass, throw or twist."),
 ("Bench sit-up", "Core", "Bench", "core", "Anchor the feet and sit up from a bench with control."),
 ("Side crunch", "Core", "Bodyweight", "core", "Lying on your side, or standing, crunch the elbow toward the knee."),
 ("Standing twist", "Core", "Cable or landmine", "core", "Rotate through the torso with straight arms and stable hips."),
 ("Hand to opposite hand", "Core", "Bodyweight", "core", "Lying crunch passing the hands across the body."),
 ("Hand to opposite foot", "Core", "Bodyweight", "core", "Reach the hand toward the opposite foot or bent knee as you crunch."),
 ("Hand to knee crunch", "Core", "Bodyweight", "core", "Crunch bringing knee and hand together."),
 ("Bicycle crunch", "Core", "Bodyweight", "core", "Alternate elbow to opposite knee while the other leg extends."),
 ("Plank row", "Core", "Dumbbells", "core", "Plank on dumbbells and row each side with the hips square."),
 ("Plank step-up", "Core", "Bench or box", "core", "From plank, step one hand then the other onto a box and back down."),
 ("V-up", "Core", "Bodyweight", "core", "Lie flat and lift the arms and legs together to form a V."),
 ("Hanging knee raise", "Core", "Bar or dip bar", "core", "Hang or use a dip station and curl the knees to the chest. Add a twist for the obliques."),
 ("Leg push down", "Core", "Partner", "core", "Lying on your back, lower the legs against a partner's push and control them back up."),
 ("Turkish get-up", "Full body", "Kettlebell", "core", "Move from lying to standing with the weight overhead, one controlled step at a time. Half version first."),
 ("Hip drop", "Core", "Bodyweight", "core", "From a side plank, drop and lift the hip."),
 ("Leg raise", "Core", "Bench or floor", "core", "Raise straight legs to vertical and lower slowly. Reverse and windmill versions are used too."),
 ("Ball to chin", "Core", "Medicine ball", "core", "Crunch up and touch the ball to the chin."),
 ("Frame sit-up", "Core", "Bodyweight", "core", "Sit up with the hands framing the head, lowering slowly."),
 ("Butterfly sit-up", "Core", "Bodyweight", "core", "Soles of the feet together, knees out, and sit up."),
 ("Crunch", "Core", "Bodyweight or Swiss ball", "core", "Lift the shoulders off the floor, ribs toward the hips, without pulling on the neck. Pass version used too."),
 ("Plank rotation", "Core", "Bodyweight", "core", "From plank, rotate into a side plank and back."),
 ("Plank tap", "Core", "Bodyweight or ball", "core", "In plank, tap the opposite shoulder or a ball without letting the hips sway."),
 ("Flutter kick", "Core", "Bodyweight", "core", "Lying on your back, small quick alternating kicks with the legs just above the floor."),
 ("Criss-cross", "Core", "Bodyweight", "core", "Lying legs cross over one another in a scissor motion."),
 ("Scissors", "Core", "Bodyweight", "core", "Lying legs open and close in a controlled scissor."),
 ("Windmill", "Core", "Bodyweight", "core", "Rotate the torso to reach one hand to the opposite toes."),
 ("Side bend", "Core", "Dumbbell", "core", "Stand tall and lean to one side with a dumbbell, return using the obliques."),
 ("TRX pike", "Core", "TRX", "core", "Feet in the straps, lift the hips toward the ceiling into a pike."),
 ("Ankle touch", "Core", "Bodyweight", "core", "Lying with the knees bent, crunch sideways to touch each ankle."),
 ("Swiss ball knees in", "Core", "Swiss ball", "core", "Shins on the ball in a push-up position, pull the knees to the chest."),
 ("Swiss ball up n down", "Core", "Swiss ball", "core", "Roll the ball and move through a slow up and down pattern with a tight core."),
 ("Knees to chest", "Core", "Bodyweight", "core", "Lying or hanging, pull the knees to the chest."),
 ("Single arm ball throw", "Core", "Medicine ball", "core", "Throw the ball one-handed with rotation, catch and repeat."),
]
